with character_item_equipment as (
    select
        *,
        date as snapshot_date
    from {{ source('nexon', 'character_item_equipment') }}
),

p1 as (
    select
        snapshot_date,
        ocid,
        e1 ->> 'item_equipment_slot' as item_equipment_slot,
        e1 ->> 'item_equipment_part' as item_equipment_part,
        e1 ->> 'item_icon' as item_icon,
        e1 ->> 'item_name' as item_name,
        e1 ->> 'soul_name' as soul_name,
        (e1 ->> 'starforce')::integer as starforce,
        (e1 ->> 'growth_exp')::integer as growth_exp,
        e1 ->> 'date_expire' as date_expire,
        e1 ->> 'item_gender' as item_gender,
        e1 ->> 'soul_option' as soul_option,
        (e1 ->> 'growth_level')::integer as growth_level,
        (e1 ->> 'cuttable_count')::integer as cuttable_count,
        (e1 ->> 'freestyle_flag')::boolean as is_freestyle,
        (e1 ->> 'scroll_upgrade')::integer as scroll_upgrade,
        (e1 #>> '{item_add_option,dex}')::integer as item_add_option_dex,
        (e1 #>> '{item_add_option,int}')::integer as item_add_option_int,
        (e1 #>> '{item_add_option,luk}')::integer as item_add_option_luk,
        (e1 #>> '{item_add_option,str}')::integer as item_add_option_str,
        (e1 #>> '{item_add_option,jump}')::integer as item_add_option_jump,
        (e1 #>> '{item_add_option,armor}')::integer as item_add_option_armor,
        (e1 #>> '{item_add_option,speed}')::integer as item_add_option_speed,
        (e1 #>> '{item_add_option,damage}')::integer as item_add_option_damage,
        (e1 #>> '{item_add_option,max_hp}')::integer as item_add_option_max_hp,
        (e1 #>> '{item_add_option,max_mp}')::integer as item_add_option_max_mp,
        (e1 #>> '{item_add_option,all_stat}')::integer as item_add_option_all_stat,
        (e1 #>> '{item_add_option,boss_damage}')::integer as item_add_option_boss_damage,
        (e1 #>> '{item_add_option,magic_power}')::integer as item_add_option_magic_power,
        (e1 #>> '{item_add_option,attack_power}')::integer as item_add_option_attack_power,
        (e1 #>> '{item_add_option,equipment_level_decrease}')::integer as item_add_option_equipment_level_decrease,
        (e1 #>> '{item_etc_option,dex}')::integer as item_etc_option_dex,
        (e1 #>> '{item_etc_option,int}')::integer as item_etc_option_int,
        (e1 #>> '{item_etc_option,luk}')::integer as item_etc_option_luk,
        (e1 #>> '{item_etc_option,str}')::integer as item_etc_option_str,
        (e1 #>> '{item_etc_option,jump}')::integer as item_etc_option_jump,
        (e1 #>> '{item_etc_option,armor}')::integer as item_etc_option_armor,
        (e1 #>> '{item_etc_option,speed}')::integer as item_etc_option_speed,
        (e1 #>> '{item_etc_option,max_hp}')::integer as item_etc_option_max_hp,
        (e1 #>> '{item_etc_option,max_mp}')::integer as item_etc_option_max_mp,
        (e1 #>> '{item_etc_option,magic_power}')::integer as item_etc_option_magic_power,
        (e1 #>> '{item_etc_option,attack_power}')::integer as item_etc_option_attack_power,
        e1 ->> 'item_shape_icon' as item_shape_icon,
        e1 ->> 'item_shape_name' as item_shape_name,
        (e1 #>> '{item_base_option,dex}')::integer as item_base_option_dex,
        (e1 #>> '{item_base_option,int}')::integer as item_base_option_int,
        (e1 #>> '{item_base_option,luk}')::integer as item_base_option_luk,
        (e1 #>> '{item_base_option,str}')::integer as item_base_option_str,
        (e1 #>> '{item_base_option,jump}')::integer as item_base_option_jump,
        (e1 #>> '{item_base_option,armor}')::integer as item_base_option_armor,
        (e1 #>> '{item_base_option,speed}')::integer as item_base_option_speed,
        (e1 #>> '{item_base_option,max_hp}')::integer as item_base_option_max_hp,
        (e1 #>> '{item_base_option,max_mp}')::integer as item_base_option_max_mp,
        (e1 #>> '{item_base_option,all_stat}')::integer as item_base_option_all_stat,
        (e1 #>> '{item_base_option,boss_damage}')::integer as item_base_option_boss_damage,
        (e1 #>> '{item_base_option,magic_power}')::integer as item_base_option_magic_power,
        (e1 #>> '{item_base_option,max_hp_rate}')::integer as item_base_option_max_hp_rate,
        (e1 #>> '{item_base_option,max_mp_rate}')::integer as item_base_option_max_mp_rate,
        (e1 #>> '{item_base_option,attack_power}')::integer as item_base_option_attack_power,
        (e1 #>> '{item_base_option,base_equipment_level}')::integer as item_base_option_base_equipment_level,
        (e1 #>> '{item_base_option,ignore_monster_armor}')::integer as item_base_option_ignore_monster_armor,
        e1 ->> 'item_description' as item_description,
        (e1 #>> '{item_total_option,dex}')::integer as item_total_option_dex,
        (e1 #>> '{item_total_option,int}')::integer as item_total_option_int,
        (e1 #>> '{item_total_option,luk}')::integer as item_total_option_luk,
        (e1 #>> '{item_total_option,str}')::integer as item_total_option_str,
        (e1 #>> '{item_total_option,jump}')::integer as item_total_option_jump,
        (e1 #>> '{item_total_option,armor}')::integer as item_total_option_armor,
        (e1 #>> '{item_total_option,speed}')::integer as item_total_option_speed,
        (e1 #>> '{item_total_option,damage}')::integer as item_total_option_damage,
        (e1 #>> '{item_total_option,max_hp}')::integer as item_total_option_max_hp,
        (e1 #>> '{item_total_option,max_mp}')::integer as item_total_option_max_mp,
        (e1 #>> '{item_total_option,all_stat}')::integer as item_total_option_all_stat,
        (e1 #>> '{item_total_option,boss_damage}')::integer as item_total_option_boss_damage,
        (e1 #>> '{item_total_option,magic_power}')::integer as item_total_option_magic_power,
        (e1 #>> '{item_total_option,max_hp_rate}')::integer as item_total_option_max_hp_rate,
        (e1 #>> '{item_total_option,max_mp_rate}')::integer as item_total_option_max_mp_rate,
        (e1 #>> '{item_total_option,attack_power}')::integer as item_total_option_attack_power,
        (e1 #>> '{item_total_option,ignore_monster_armor}')::integer as item_total_option_ignore_monster_armor,
        (e1 #>> '{item_total_option,equipment_level_decrease}')::integer as item_total_option_equipment_level_decrease,
        case
            when e1 ->> 'golden_hammer_flag' is null then null
            when e1 ->> 'golden_hammer_flag' = '미적용' then false
            else true
        end as has_golden_hammer,
        e1 ->> 'potential_option_1' as potential_option_1,
        e1 ->> 'potential_option_2' as potential_option_2,
        e1 ->> 'potential_option_3' as potential_option_3,
        (e1 ->> 'special_ring_level')::integer as special_ring_level,
        (e1 #>> '{item_starforce_option,dex}')::integer as item_starforce_option_dex,
        (e1 #>> '{item_starforce_option,int}')::integer as item_starforce_option_int,
        (e1 #>> '{item_starforce_option,luk}')::integer as item_starforce_option_luk,
        (e1 #>> '{item_starforce_option,str}')::integer as item_starforce_option_str,
        (e1 #>> '{item_starforce_option,jump}')::integer as item_starforce_option_jump,
        (e1 #>> '{item_starforce_option,armor}')::integer as item_starforce_option_armor,
        (e1 #>> '{item_starforce_option,speed}')::integer as item_starforce_option_speed,
        (e1 #>> '{item_starforce_option,max_hp}')::integer as item_starforce_option_max_hp,
        (e1 #>> '{item_starforce_option,max_mp}')::integer as item_starforce_option_max_mp,
        (e1 #>> '{item_starforce_option,magic_power}')::integer as item_starforce_option_magic_power,
        (e1 #>> '{item_starforce_option,attack_power}')::integer as item_starforce_option_attack_power,
        (e1 ->> 'potential_option_flag')::boolean as has_potential_option,
        case
            when e1 ->> 'starforce_scroll_flag' is null then null
            when e1 ->> 'starforce_scroll_flag' = '미사용' then false
            else true
        end as has_starforce_scroll,
        e1 ->> 'potential_option_grade' as potential_option_grade,
        (e1 #>> '{item_exceptional_option,dex}')::integer as item_exceptional_option_dex,
        (e1 #>> '{item_exceptional_option,int}')::integer as item_exceptional_option_int,
        (e1 #>> '{item_exceptional_option,luk}')::integer as item_exceptional_option_luk,
        (e1 #>> '{item_exceptional_option,str}')::integer as item_exceptional_option_str,
        (e1 #>> '{item_exceptional_option,max_hp}')::integer as item_exceptional_option_max_hp,
        (e1 #>> '{item_exceptional_option,max_mp}')::integer as item_exceptional_option_max_mp,
        (e1 #>> '{item_exceptional_option,magic_power}')::integer as item_exceptional_option_magic_power,
        (e1 #>> '{item_exceptional_option,attack_power}')::integer as item_exceptional_option_attack_power,
        (e1 #>> '{item_exceptional_option,exceptional_upgrade}')::integer as item_exceptional_option_exceptional_upgrade,
        (e1 ->> 'scroll_resilience_count')::integer as scroll_resilience_count,
        (e1 ->> 'equipment_level_increase')::integer as equipment_level_increase,
        (e1 ->> 'scroll_upgradeable_count')::integer as scroll_upgradeable_count,
        e1 ->> 'additional_potential_option_1' as additional_potential_option_1,
        e1 ->> 'additional_potential_option_2' as additional_potential_option_2,
        e1 ->> 'additional_potential_option_3' as additional_potential_option_3,
        (e1 ->> 'additional_potential_option_flag')::boolean as has_additional_potential_option,
        e1 ->> 'additional_potential_option_grade' as additional_potential_option_grade
    from character_item_equipment,
        lateral jsonb_array_elements(item_equipment_preset_1) as e1
),

p2 as (
    select
        snapshot_date,
        ocid,
        e2 ->> 'item_equipment_slot' as item_equipment_slot,
        e2 ->> 'item_equipment_part' as item_equipment_part,
        e2 ->> 'item_icon' as item_icon,
        e2 ->> 'item_name' as item_name,
        e2 ->> 'soul_name' as soul_name,
        (e2 ->> 'starforce')::integer as starforce,
        (e2 ->> 'growth_exp')::integer as growth_exp,
        e2 ->> 'date_expire' as date_expire,
        e2 ->> 'item_gender' as item_gender,
        e2 ->> 'soul_option' as soul_option,
        (e2 ->> 'growth_level')::integer as growth_level,
        (e2 ->> 'cuttable_count')::integer as cuttable_count,
        (e2 ->> 'freestyle_flag')::boolean as is_freestyle,
        (e2 ->> 'scroll_upgrade')::integer as scroll_upgrade,
        (e2 #>> '{item_add_option,dex}')::integer as item_add_option_dex,
        (e2 #>> '{item_add_option,int}')::integer as item_add_option_int,
        (e2 #>> '{item_add_option,luk}')::integer as item_add_option_luk,
        (e2 #>> '{item_add_option,str}')::integer as item_add_option_str,
        (e2 #>> '{item_add_option,jump}')::integer as item_add_option_jump,
        (e2 #>> '{item_add_option,armor}')::integer as item_add_option_armor,
        (e2 #>> '{item_add_option,speed}')::integer as item_add_option_speed,
        (e2 #>> '{item_add_option,damage}')::integer as item_add_option_damage,
        (e2 #>> '{item_add_option,max_hp}')::integer as item_add_option_max_hp,
        (e2 #>> '{item_add_option,max_mp}')::integer as item_add_option_max_mp,
        (e2 #>> '{item_add_option,all_stat}')::integer as item_add_option_all_stat,
        (e2 #>> '{item_add_option,boss_damage}')::integer as item_add_option_boss_damage,
        (e2 #>> '{item_add_option,magic_power}')::integer as item_add_option_magic_power,
        (e2 #>> '{item_add_option,attack_power}')::integer as item_add_option_attack_power,
        (e2 #>> '{item_add_option,equipment_level_decrease}')::integer as item_add_option_equipment_level_decrease,
        (e2 #>> '{item_etc_option,dex}')::integer as item_etc_option_dex,
        (e2 #>> '{item_etc_option,int}')::integer as item_etc_option_int,
        (e2 #>> '{item_etc_option,luk}')::integer as item_etc_option_luk,
        (e2 #>> '{item_etc_option,str}')::integer as item_etc_option_str,
        (e2 #>> '{item_etc_option,jump}')::integer as item_etc_option_jump,
        (e2 #>> '{item_etc_option,armor}')::integer as item_etc_option_armor,
        (e2 #>> '{item_etc_option,speed}')::integer as item_etc_option_speed,
        (e2 #>> '{item_etc_option,max_hp}')::integer as item_etc_option_max_hp,
        (e2 #>> '{item_etc_option,max_mp}')::integer as item_etc_option_max_mp,
        (e2 #>> '{item_etc_option,magic_power}')::integer as item_etc_option_magic_power,
        (e2 #>> '{item_etc_option,attack_power}')::integer as item_etc_option_attack_power,
        e2 ->> 'item_shape_icon' as item_shape_icon,
        e2 ->> 'item_shape_name' as item_shape_name,
        (e2 #>> '{item_base_option,dex}')::integer as item_base_option_dex,
        (e2 #>> '{item_base_option,int}')::integer as item_base_option_int,
        (e2 #>> '{item_base_option,luk}')::integer as item_base_option_luk,
        (e2 #>> '{item_base_option,str}')::integer as item_base_option_str,
        (e2 #>> '{item_base_option,jump}')::integer as item_base_option_jump,
        (e2 #>> '{item_base_option,armor}')::integer as item_base_option_armor,
        (e2 #>> '{item_base_option,speed}')::integer as item_base_option_speed,
        (e2 #>> '{item_base_option,max_hp}')::integer as item_base_option_max_hp,
        (e2 #>> '{item_base_option,max_mp}')::integer as item_base_option_max_mp,
        (e2 #>> '{item_base_option,all_stat}')::integer as item_base_option_all_stat,
        (e2 #>> '{item_base_option,boss_damage}')::integer as item_base_option_boss_damage,
        (e2 #>> '{item_base_option,magic_power}')::integer as item_base_option_magic_power,
        (e2 #>> '{item_base_option,max_hp_rate}')::integer as item_base_option_max_hp_rate,
        (e2 #>> '{item_base_option,max_mp_rate}')::integer as item_base_option_max_mp_rate,
        (e2 #>> '{item_base_option,attack_power}')::integer as item_base_option_attack_power,
        (e2 #>> '{item_base_option,base_equipment_level}')::integer as item_base_option_base_equipment_level,
        (e2 #>> '{item_base_option,ignore_monster_armor}')::integer as item_base_option_ignore_monster_armor,
        e2 ->> 'item_description' as item_description,
        (e2 #>> '{item_total_option,dex}')::integer as item_total_option_dex,
        (e2 #>> '{item_total_option,int}')::integer as item_total_option_int,
        (e2 #>> '{item_total_option,luk}')::integer as item_total_option_luk,
        (e2 #>> '{item_total_option,str}')::integer as item_total_option_str,
        (e2 #>> '{item_total_option,jump}')::integer as item_total_option_jump,
        (e2 #>> '{item_total_option,armor}')::integer as item_total_option_armor,
        (e2 #>> '{item_total_option,speed}')::integer as item_total_option_speed,
        (e2 #>> '{item_total_option,damage}')::integer as item_total_option_damage,
        (e2 #>> '{item_total_option,max_hp}')::integer as item_total_option_max_hp,
        (e2 #>> '{item_total_option,max_mp}')::integer as item_total_option_max_mp,
        (e2 #>> '{item_total_option,all_stat}')::integer as item_total_option_all_stat,
        (e2 #>> '{item_total_option,boss_damage}')::integer as item_total_option_boss_damage,
        (e2 #>> '{item_total_option,magic_power}')::integer as item_total_option_magic_power,
        (e2 #>> '{item_total_option,max_hp_rate}')::integer as item_total_option_max_hp_rate,
        (e2 #>> '{item_total_option,max_mp_rate}')::integer as item_total_option_max_mp_rate,
        (e2 #>> '{item_total_option,attack_power}')::integer as item_total_option_attack_power,
        (e2 #>> '{item_total_option,ignore_monster_armor}')::integer as item_total_option_ignore_monster_armor,
        (e2 #>> '{item_total_option,equipment_level_decrease}')::integer as item_total_option_equipment_level_decrease,
        case
            when e2 ->> 'golden_hammer_flag' is null then null
            when e2 ->> 'golden_hammer_flag' = '미적용' then false
            else true
        end as has_golden_hammer,
        e2 ->> 'potential_option_1' as potential_option_1,
        e2 ->> 'potential_option_2' as potential_option_2,
        e2 ->> 'potential_option_3' as potential_option_3,
        (e2 ->> 'special_ring_level')::integer as special_ring_level,
        (e2 #>> '{item_starforce_option,dex}')::integer as item_starforce_option_dex,
        (e2 #>> '{item_starforce_option,int}')::integer as item_starforce_option_int,
        (e2 #>> '{item_starforce_option,luk}')::integer as item_starforce_option_luk,
        (e2 #>> '{item_starforce_option,str}')::integer as item_starforce_option_str,
        (e2 #>> '{item_starforce_option,jump}')::integer as item_starforce_option_jump,
        (e2 #>> '{item_starforce_option,armor}')::integer as item_starforce_option_armor,
        (e2 #>> '{item_starforce_option,speed}')::integer as item_starforce_option_speed,
        (e2 #>> '{item_starforce_option,max_hp}')::integer as item_starforce_option_max_hp,
        (e2 #>> '{item_starforce_option,max_mp}')::integer as item_starforce_option_max_mp,
        (e2 #>> '{item_starforce_option,magic_power}')::integer as item_starforce_option_magic_power,
        (e2 #>> '{item_starforce_option,attack_power}')::integer as item_starforce_option_attack_power,
        (e2 ->> 'potential_option_flag')::boolean as has_potential_option,
        case
            when e2 ->> 'starforce_scroll_flag' is null then null
            when e2 ->> 'starforce_scroll_flag' = '미사용' then false
            else true
        end as has_starforce_scroll,
        e2 ->> 'potential_option_grade' as potential_option_grade,
        (e2 #>> '{item_exceptional_option,dex}')::integer as item_exceptional_option_dex,
        (e2 #>> '{item_exceptional_option,int}')::integer as item_exceptional_option_int,
        (e2 #>> '{item_exceptional_option,luk}')::integer as item_exceptional_option_luk,
        (e2 #>> '{item_exceptional_option,str}')::integer as item_exceptional_option_str,
        (e2 #>> '{item_exceptional_option,max_hp}')::integer as item_exceptional_option_max_hp,
        (e2 #>> '{item_exceptional_option,max_mp}')::integer as item_exceptional_option_max_mp,
        (e2 #>> '{item_exceptional_option,magic_power}')::integer as item_exceptional_option_magic_power,
        (e2 #>> '{item_exceptional_option,attack_power}')::integer as item_exceptional_option_attack_power,
        (e2 #>> '{item_exceptional_option,exceptional_upgrade}')::integer as item_exceptional_option_exceptional_upgrade,
        (e2 ->> 'scroll_resilience_count')::integer as scroll_resilience_count,
        (e2 ->> 'equipment_level_increase')::integer as equipment_level_increase,
        (e2 ->> 'scroll_upgradeable_count')::integer as scroll_upgradeable_count,
        e2 ->> 'additional_potential_option_1' as additional_potential_option_1,
        e2 ->> 'additional_potential_option_2' as additional_potential_option_2,
        e2 ->> 'additional_potential_option_3' as additional_potential_option_3,
        (e2 ->> 'additional_potential_option_flag')::boolean as has_additional_potential_option,
        e2 ->> 'additional_potential_option_grade' as additional_potential_option_grade
    from character_item_equipment,
        lateral jsonb_array_elements(item_equipment_preset_2) as e2
),

p3 as (
    select
        snapshot_date,
        ocid,
        e3 ->> 'item_equipment_slot' as item_equipment_slot,
        e3 ->> 'item_equipment_part' as item_equipment_part,
        e3 ->> 'item_icon' as item_icon,
        e3 ->> 'item_name' as item_name,
        e3 ->> 'soul_name' as soul_name,
        (e3 ->> 'starforce')::integer as starforce,
        (e3 ->> 'growth_exp')::integer as growth_exp,
        e3 ->> 'date_expire' as date_expire,
        e3 ->> 'item_gender' as item_gender,
        e3 ->> 'soul_option' as soul_option,
        (e3 ->> 'growth_level')::integer as growth_level,
        (e3 ->> 'cuttable_count')::integer as cuttable_count,
        (e3 ->> 'freestyle_flag')::boolean as is_freestyle,
        (e3 ->> 'scroll_upgrade')::integer as scroll_upgrade,
        (e3 #>> '{item_add_option,dex}')::integer as item_add_option_dex,
        (e3 #>> '{item_add_option,int}')::integer as item_add_option_int,
        (e3 #>> '{item_add_option,luk}')::integer as item_add_option_luk,
        (e3 #>> '{item_add_option,str}')::integer as item_add_option_str,
        (e3 #>> '{item_add_option,jump}')::integer as item_add_option_jump,
        (e3 #>> '{item_add_option,armor}')::integer as item_add_option_armor,
        (e3 #>> '{item_add_option,speed}')::integer as item_add_option_speed,
        (e3 #>> '{item_add_option,damage}')::integer as item_add_option_damage,
        (e3 #>> '{item_add_option,max_hp}')::integer as item_add_option_max_hp,
        (e3 #>> '{item_add_option,max_mp}')::integer as item_add_option_max_mp,
        (e3 #>> '{item_add_option,all_stat}')::integer as item_add_option_all_stat,
        (e3 #>> '{item_add_option,boss_damage}')::integer as item_add_option_boss_damage,
        (e3 #>> '{item_add_option,magic_power}')::integer as item_add_option_magic_power,
        (e3 #>> '{item_add_option,attack_power}')::integer as item_add_option_attack_power,
        (e3 #>> '{item_add_option,equipment_level_decrease}')::integer as item_add_option_equipment_level_decrease,
        (e3 #>> '{item_etc_option,dex}')::integer as item_etc_option_dex,
        (e3 #>> '{item_etc_option,int}')::integer as item_etc_option_int,
        (e3 #>> '{item_etc_option,luk}')::integer as item_etc_option_luk,
        (e3 #>> '{item_etc_option,str}')::integer as item_etc_option_str,
        (e3 #>> '{item_etc_option,jump}')::integer as item_etc_option_jump,
        (e3 #>> '{item_etc_option,armor}')::integer as item_etc_option_armor,
        (e3 #>> '{item_etc_option,speed}')::integer as item_etc_option_speed,
        (e3 #>> '{item_etc_option,max_hp}')::integer as item_etc_option_max_hp,
        (e3 #>> '{item_etc_option,max_mp}')::integer as item_etc_option_max_mp,
        (e3 #>> '{item_etc_option,magic_power}')::integer as item_etc_option_magic_power,
        (e3 #>> '{item_etc_option,attack_power}')::integer as item_etc_option_attack_power,
        e3 ->> 'item_shape_icon' as item_shape_icon,
        e3 ->> 'item_shape_name' as item_shape_name,
        (e3 #>> '{item_base_option,dex}')::integer as item_base_option_dex,
        (e3 #>> '{item_base_option,int}')::integer as item_base_option_int,
        (e3 #>> '{item_base_option,luk}')::integer as item_base_option_luk,
        (e3 #>> '{item_base_option,str}')::integer as item_base_option_str,
        (e3 #>> '{item_base_option,jump}')::integer as item_base_option_jump,
        (e3 #>> '{item_base_option,armor}')::integer as item_base_option_armor,
        (e3 #>> '{item_base_option,speed}')::integer as item_base_option_speed,
        (e3 #>> '{item_base_option,max_hp}')::integer as item_base_option_max_hp,
        (e3 #>> '{item_base_option,max_mp}')::integer as item_base_option_max_mp,
        (e3 #>> '{item_base_option,all_stat}')::integer as item_base_option_all_stat,
        (e3 #>> '{item_base_option,boss_damage}')::integer as item_base_option_boss_damage,
        (e3 #>> '{item_base_option,magic_power}')::integer as item_base_option_magic_power,
        (e3 #>> '{item_base_option,max_hp_rate}')::integer as item_base_option_max_hp_rate,
        (e3 #>> '{item_base_option,max_mp_rate}')::integer as item_base_option_max_mp_rate,
        (e3 #>> '{item_base_option,attack_power}')::integer as item_base_option_attack_power,
        (e3 #>> '{item_base_option,base_equipment_level}')::integer as item_base_option_base_equipment_level,
        (e3 #>> '{item_base_option,ignore_monster_armor}')::integer as item_base_option_ignore_monster_armor,
        e3 ->> 'item_description' as item_description,
        (e3 #>> '{item_total_option,dex}')::integer as item_total_option_dex,
        (e3 #>> '{item_total_option,int}')::integer as item_total_option_int,
        (e3 #>> '{item_total_option,luk}')::integer as item_total_option_luk,
        (e3 #>> '{item_total_option,str}')::integer as item_total_option_str,
        (e3 #>> '{item_total_option,jump}')::integer as item_total_option_jump,
        (e3 #>> '{item_total_option,armor}')::integer as item_total_option_armor,
        (e3 #>> '{item_total_option,speed}')::integer as item_total_option_speed,
        (e3 #>> '{item_total_option,damage}')::integer as item_total_option_damage,
        (e3 #>> '{item_total_option,max_hp}')::integer as item_total_option_max_hp,
        (e3 #>> '{item_total_option,max_mp}')::integer as item_total_option_max_mp,
        (e3 #>> '{item_total_option,all_stat}')::integer as item_total_option_all_stat,
        (e3 #>> '{item_total_option,boss_damage}')::integer as item_total_option_boss_damage,
        (e3 #>> '{item_total_option,magic_power}')::integer as item_total_option_magic_power,
        (e3 #>> '{item_total_option,max_hp_rate}')::integer as item_total_option_max_hp_rate,
        (e3 #>> '{item_total_option,max_mp_rate}')::integer as item_total_option_max_mp_rate,
        (e3 #>> '{item_total_option,attack_power}')::integer as item_total_option_attack_power,
        (e3 #>> '{item_total_option,ignore_monster_armor}')::integer as item_total_option_ignore_monster_armor,
        (e3 #>> '{item_total_option,equipment_level_decrease}')::integer as item_total_option_equipment_level_decrease,
        case
            when e3 ->> 'golden_hammer_flag' is null then null
            when e3 ->> 'golden_hammer_flag' = '미적용' then false
            else true
        end as has_golden_hammer,
        e3 ->> 'potential_option_1' as potential_option_1,
        e3 ->> 'potential_option_2' as potential_option_2,
        e3 ->> 'potential_option_3' as potential_option_3,
        (e3 ->> 'special_ring_level')::integer as special_ring_level,
        (e3 #>> '{item_starforce_option,dex}')::integer as item_starforce_option_dex,
        (e3 #>> '{item_starforce_option,int}')::integer as item_starforce_option_int,
        (e3 #>> '{item_starforce_option,luk}')::integer as item_starforce_option_luk,
        (e3 #>> '{item_starforce_option,str}')::integer as item_starforce_option_str,
        (e3 #>> '{item_starforce_option,jump}')::integer as item_starforce_option_jump,
        (e3 #>> '{item_starforce_option,armor}')::integer as item_starforce_option_armor,
        (e3 #>> '{item_starforce_option,speed}')::integer as item_starforce_option_speed,
        (e3 #>> '{item_starforce_option,max_hp}')::integer as item_starforce_option_max_hp,
        (e3 #>> '{item_starforce_option,max_mp}')::integer as item_starforce_option_max_mp,
        (e3 #>> '{item_starforce_option,magic_power}')::integer as item_starforce_option_magic_power,
        (e3 #>> '{item_starforce_option,attack_power}')::integer as item_starforce_option_attack_power,
        (e3 ->> 'potential_option_flag')::boolean as has_potential_option,
        case
            when e3 ->> 'starforce_scroll_flag' is null then null
            when e3 ->> 'starforce_scroll_flag' = '미사용' then false
            else true
        end as has_starforce_scroll,
        e3 ->> 'potential_option_grade' as potential_option_grade,
        (e3 #>> '{item_exceptional_option,dex}')::integer as item_exceptional_option_dex,
        (e3 #>> '{item_exceptional_option,int}')::integer as item_exceptional_option_int,
        (e3 #>> '{item_exceptional_option,luk}')::integer as item_exceptional_option_luk,
        (e3 #>> '{item_exceptional_option,str}')::integer as item_exceptional_option_str,
        (e3 #>> '{item_exceptional_option,max_hp}')::integer as item_exceptional_option_max_hp,
        (e3 #>> '{item_exceptional_option,max_mp}')::integer as item_exceptional_option_max_mp,
        (e3 #>> '{item_exceptional_option,magic_power}')::integer as item_exceptional_option_magic_power,
        (e3 #>> '{item_exceptional_option,attack_power}')::integer as item_exceptional_option_attack_power,
        (e3 #>> '{item_exceptional_option,exceptional_upgrade}')::integer as item_exceptional_option_exceptional_upgrade,
        (e3 ->> 'scroll_resilience_count')::integer as scroll_resilience_count,
        (e3 ->> 'equipment_level_increase')::integer as equipment_level_increase,
        (e3 ->> 'scroll_upgradeable_count')::integer as scroll_upgradeable_count,
        e3 ->> 'additional_potential_option_1' as additional_potential_option_1,
        e3 ->> 'additional_potential_option_2' as additional_potential_option_2,
        e3 ->> 'additional_potential_option_3' as additional_potential_option_3,
        (e3 ->> 'additional_potential_option_flag')::boolean as has_additional_potential_option,
        e3 ->> 'additional_potential_option_grade' as additional_potential_option_grade
    from character_item_equipment,
        lateral jsonb_array_elements(item_equipment_preset_3) as e3
),

item_equipment_presets as (
    select
        snapshot_date,
        ocid,
        item_equipment_slot,
        coalesce(p1.item_equipment_part, p2.item_equipment_part, p3.item_equipment_part) as item_equipment_part,
        p1.item_icon as item_equipment_preset_1__icon,
        p1.item_name as item_equipment_preset_1__name,
        p1.soul_name as item_equipment_preset_1__soul_name,
        p1.starforce as item_equipment_preset_1__starforce,
        p1.growth_exp as item_equipment_preset_1__growth_exp,
        p1.date_expire as item_equipment_preset_1__date_expire,
        p1.item_gender as item_equipment_preset_1__gender,
        p1.soul_option as item_equipment_preset_1__soul_option,
        p1.growth_level as item_equipment_preset_1__growth_level,
        p1.cuttable_count as item_equipment_preset_1__cuttable_count,
        p1.is_freestyle as is_item_equipment_preset_1__freestyle,
        p1.scroll_upgrade as item_equipment_preset_1__scroll_upgrade,
        p1.item_add_option_dex as item_equipment_preset_1__add_option__dex,
        p1.item_add_option_int as item_equipment_preset_1__add_option__int,
        p1.item_add_option_luk as item_equipment_preset_1__add_option__luk,
        p1.item_add_option_str as item_equipment_preset_1__add_option__str,
        p1.item_add_option_jump as item_equipment_preset_1__add_option__jump,
        p1.item_add_option_armor as item_equipment_preset_1__add_option__armor,
        p1.item_add_option_speed as item_equipment_preset_1__add_option__speed,
        p1.item_add_option_damage as item_equipment_preset_1__add_option__damage,
        p1.item_add_option_max_hp as item_equipment_preset_1__add_option__max_hp,
        p1.item_add_option_max_mp as item_equipment_preset_1__add_option__max_mp,
        p1.item_add_option_all_stat as item_equipment_preset_1__add_option__all_stat,
        p1.item_add_option_boss_damage as item_equipment_preset_1__add_option__boss_damage,
        p1.item_add_option_magic_power as item_equipment_preset_1__add_option__magic_power,
        p1.item_add_option_attack_power as item_equipment_preset_1__add_option__attack_power,
        p1.item_add_option_equipment_level_decrease as item_equipment_preset_1__add_option__equipment_level_decrease,
        p1.item_etc_option_dex as item_equipment_preset_1__etc_option__dex,
        p1.item_etc_option_int as item_equipment_preset_1__etc_option__int,
        p1.item_etc_option_luk as item_equipment_preset_1__etc_option__luk,
        p1.item_etc_option_str as item_equipment_preset_1__etc_option__str,
        p1.item_etc_option_jump as item_equipment_preset_1__etc_option__jump,
        p1.item_etc_option_armor as item_equipment_preset_1__etc_option__armor,
        p1.item_etc_option_speed as item_equipment_preset_1__etc_option__speed,
        p1.item_etc_option_max_hp as item_equipment_preset_1__etc_option__max_hp,
        p1.item_etc_option_max_mp as item_equipment_preset_1__etc_option__max_mp,
        p1.item_etc_option_magic_power as item_equipment_preset_1__etc_option__magic_power,
        p1.item_etc_option_attack_power as item_equipment_preset_1__etc_option__attack_power,
        p1.item_shape_icon as item_equipment_preset_1__shape_icon,
        p1.item_shape_name as item_equipment_preset_1__shape_name,
        p1.item_base_option_dex as item_equipment_preset_1__base_option__dex,
        p1.item_base_option_int as item_equipment_preset_1__base_option__int,
        p1.item_base_option_luk as item_equipment_preset_1__base_option__luk,
        p1.item_base_option_str as item_equipment_preset_1__base_option__str,
        p1.item_base_option_jump as item_equipment_preset_1__base_option__jump,
        p1.item_base_option_armor as item_equipment_preset_1__base_option__armor,
        p1.item_base_option_speed as item_equipment_preset_1__base_option__speed,
        p1.item_base_option_max_hp as item_equipment_preset_1__base_option__max_hp,
        p1.item_base_option_max_mp as item_equipment_preset_1__base_option__max_mp,
        p1.item_base_option_all_stat as item_equipment_preset_1__base_option__all_stat,
        p1.item_base_option_boss_damage as item_equipment_preset_1__base_option__boss_damage,
        p1.item_base_option_magic_power as item_equipment_preset_1__base_option__magic_power,
        p1.item_base_option_max_hp_rate as item_equipment_preset_1__base_option__max_hp_rate,
        p1.item_base_option_max_mp_rate as item_equipment_preset_1__base_option__max_mp_rate,
        p1.item_base_option_attack_power as item_equipment_preset_1__base_option__attack_power,
        p1.item_base_option_base_equipment_level as item_equipment_preset_1__base_option__base_equipment_level,
        p1.item_base_option_ignore_monster_armor as item_equipment_preset_1__base_option__ignore_monster_armor,
        p1.item_description as item_equipment_preset_1__description,
        p1.item_total_option_dex as item_equipment_preset_1__total_option__dex,
        p1.item_total_option_int as item_equipment_preset_1__total_option__int,
        p1.item_total_option_luk as item_equipment_preset_1__total_option__luk,
        p1.item_total_option_str as item_equipment_preset_1__total_option__str,
        p1.item_total_option_jump as item_equipment_preset_1__total_option__jump,
        p1.item_total_option_armor as item_equipment_preset_1__total_option__armor,
        p1.item_total_option_speed as item_equipment_preset_1__total_option__speed,
        p1.item_total_option_damage as item_equipment_preset_1__total_option__damage,
        p1.item_total_option_max_hp as item_equipment_preset_1__total_option__max_hp,
        p1.item_total_option_max_mp as item_equipment_preset_1__total_option__max_mp,
        p1.item_total_option_all_stat as item_equipment_preset_1__total_option__all_stat,
        p1.item_total_option_boss_damage as item_equipment_preset_1__total_option__boss_damage,
        p1.item_total_option_magic_power as item_equipment_preset_1__total_option__magic_power,
        p1.item_total_option_max_hp_rate as item_equipment_preset_1__total_option__max_hp_rate,
        p1.item_total_option_max_mp_rate as item_equipment_preset_1__total_option__max_mp_rate,
        p1.item_total_option_attack_power as item_equipment_preset_1__total_option__attack_power,
        p1.item_total_option_ignore_monster_armor as item_equipment_preset_1__total_option__ignore_monster_armor,
        p1.item_total_option_equipment_level_decrease as item_equipment_preset_1__total_option__equipment_level_decrease,
        p1.has_golden_hammer as has_item_equipment_preset_1__golden_hammer,
        p1.potential_option_1 as item_equipment_preset_1__potential_option_1,
        p1.potential_option_2 as item_equipment_preset_1__potential_option_2,
        p1.potential_option_3 as item_equipment_preset_1__potential_option_3,
        p1.special_ring_level as item_equipment_preset_1__special_ring_level,
        p1.item_starforce_option_dex as item_equipment_preset_1__starforce_option__dex,
        p1.item_starforce_option_int as item_equipment_preset_1__starforce_option__int,
        p1.item_starforce_option_luk as item_equipment_preset_1__starforce_option__luk,
        p1.item_starforce_option_str as item_equipment_preset_1__starforce_option__str,
        p1.item_starforce_option_jump as item_equipment_preset_1__starforce_option__jump,
        p1.item_starforce_option_armor as item_equipment_preset_1__starforce_option__armor,
        p1.item_starforce_option_speed as item_equipment_preset_1__starforce_option__speed,
        p1.item_starforce_option_max_hp as item_equipment_preset_1__starforce_option__max_hp,
        p1.item_starforce_option_max_mp as item_equipment_preset_1__starforce_option__max_mp,
        p1.item_starforce_option_magic_power as item_equipment_preset_1__starforce_option__magic_power,
        p1.item_starforce_option_attack_power as item_equipment_preset_1__starforce_option__attack_power,
        p1.has_potential_option as has_item_equipment_preset_1__potential_option,
        p1.has_starforce_scroll as has_item_equipment_preset_1__starforce_scroll,
        p1.potential_option_grade as item_equipment_preset_1__potential_option_grade,
        p1.item_exceptional_option_dex as item_equipment_preset_1__exceptional_option__dex,
        p1.item_exceptional_option_int as item_equipment_preset_1__exceptional_option__int,
        p1.item_exceptional_option_luk as item_equipment_preset_1__exceptional_option__luk,
        p1.item_exceptional_option_str as item_equipment_preset_1__exceptional_option__str,
        p1.item_exceptional_option_max_hp as item_equipment_preset_1__exceptional_option__max_hp,
        p1.item_exceptional_option_max_mp as item_equipment_preset_1__exceptional_option__max_mp,
        p1.item_exceptional_option_magic_power as item_equipment_preset_1__exceptional_option__magic_power,
        p1.item_exceptional_option_attack_power as item_equipment_preset_1__exceptional_option__attack_power,
        p1.item_exceptional_option_exceptional_upgrade as item_equipment_preset_1__exceptional_option__exceptional_upgrade,
        p1.scroll_resilience_count as item_equipment_preset_1__scroll_resilience_count,
        p1.equipment_level_increase as item_equipment_preset_1__equipment_level_increase,
        p1.scroll_upgradeable_count as item_equipment_preset_1__scroll_upgradeable_count,
        p1.additional_potential_option_1 as item_equipment_preset_1__additional_potential_option_1,
        p1.additional_potential_option_2 as item_equipment_preset_1__additional_potential_option_2,
        p1.additional_potential_option_3 as item_equipment_preset_1__additional_potential_option_3,
        p1.has_additional_potential_option as has_item_equipment_preset_1__additional_potential_option,
        p1.additional_potential_option_grade as item_equipment_preset_1__additional_potential_option_grade,
        p2.item_icon as item_equipment_preset_2__icon,
        p2.item_name as item_equipment_preset_2__name,
        p2.soul_name as item_equipment_preset_2__soul_name,
        p2.starforce as item_equipment_preset_2__starforce,
        p2.growth_exp as item_equipment_preset_2__growth_exp,
        p2.date_expire as item_equipment_preset_2__date_expire,
        p2.item_gender as item_equipment_preset_2__gender,
        p2.soul_option as item_equipment_preset_2__soul_option,
        p2.growth_level as item_equipment_preset_2__growth_level,
        p2.cuttable_count as item_equipment_preset_2__cuttable_count,
        p2.is_freestyle as is_item_equipment_preset_2__freestyle,
        p2.scroll_upgrade as item_equipment_preset_2__scroll_upgrade,
        p2.item_add_option_dex as item_equipment_preset_2__add_option__dex,
        p2.item_add_option_int as item_equipment_preset_2__add_option__int,
        p2.item_add_option_luk as item_equipment_preset_2__add_option__luk,
        p2.item_add_option_str as item_equipment_preset_2__add_option__str,
        p2.item_add_option_jump as item_equipment_preset_2__add_option__jump,
        p2.item_add_option_armor as item_equipment_preset_2__add_option__armor,
        p2.item_add_option_speed as item_equipment_preset_2__add_option__speed,
        p2.item_add_option_damage as item_equipment_preset_2__add_option__damage,
        p2.item_add_option_max_hp as item_equipment_preset_2__add_option__max_hp,
        p2.item_add_option_max_mp as item_equipment_preset_2__add_option__max_mp,
        p2.item_add_option_all_stat as item_equipment_preset_2__add_option__all_stat,
        p2.item_add_option_boss_damage as item_equipment_preset_2__add_option__boss_damage,
        p2.item_add_option_magic_power as item_equipment_preset_2__add_option__magic_power,
        p2.item_add_option_attack_power as item_equipment_preset_2__add_option__attack_power,
        p2.item_add_option_equipment_level_decrease as item_equipment_preset_2__add_option__equipment_level_decrease,
        p2.item_etc_option_dex as item_equipment_preset_2__etc_option__dex,
        p2.item_etc_option_int as item_equipment_preset_2__etc_option__int,
        p2.item_etc_option_luk as item_equipment_preset_2__etc_option__luk,
        p2.item_etc_option_str as item_equipment_preset_2__etc_option__str,
        p2.item_etc_option_jump as item_equipment_preset_2__etc_option__jump,
        p2.item_etc_option_armor as item_equipment_preset_2__etc_option__armor,
        p2.item_etc_option_speed as item_equipment_preset_2__etc_option__speed,
        p2.item_etc_option_max_hp as item_equipment_preset_2__etc_option__max_hp,
        p2.item_etc_option_max_mp as item_equipment_preset_2__etc_option__max_mp,
        p2.item_etc_option_magic_power as item_equipment_preset_2__etc_option__magic_power,
        p2.item_etc_option_attack_power as item_equipment_preset_2__etc_option__attack_power,
        p2.item_shape_icon as item_equipment_preset_2__shape_icon,
        p2.item_shape_name as item_equipment_preset_2__shape_name,
        p2.item_base_option_dex as item_equipment_preset_2__base_option__dex,
        p2.item_base_option_int as item_equipment_preset_2__base_option__int,
        p2.item_base_option_luk as item_equipment_preset_2__base_option__luk,
        p2.item_base_option_str as item_equipment_preset_2__base_option__str,
        p2.item_base_option_jump as item_equipment_preset_2__base_option__jump,
        p2.item_base_option_armor as item_equipment_preset_2__base_option__armor,
        p2.item_base_option_speed as item_equipment_preset_2__base_option__speed,
        p2.item_base_option_max_hp as item_equipment_preset_2__base_option__max_hp,
        p2.item_base_option_max_mp as item_equipment_preset_2__base_option__max_mp,
        p2.item_base_option_all_stat as item_equipment_preset_2__base_option__all_stat,
        p2.item_base_option_boss_damage as item_equipment_preset_2__base_option__boss_damage,
        p2.item_base_option_magic_power as item_equipment_preset_2__base_option__magic_power,
        p2.item_base_option_max_hp_rate as item_equipment_preset_2__base_option__max_hp_rate,
        p2.item_base_option_max_mp_rate as item_equipment_preset_2__base_option__max_mp_rate,
        p2.item_base_option_attack_power as item_equipment_preset_2__base_option__attack_power,
        p2.item_base_option_base_equipment_level as item_equipment_preset_2__base_option__base_equipment_level,
        p2.item_base_option_ignore_monster_armor as item_equipment_preset_2__base_option__ignore_monster_armor,
        p2.item_description as item_equipment_preset_2__description,
        p2.item_total_option_dex as item_equipment_preset_2__total_option__dex,
        p2.item_total_option_int as item_equipment_preset_2__total_option__int,
        p2.item_total_option_luk as item_equipment_preset_2__total_option__luk,
        p2.item_total_option_str as item_equipment_preset_2__total_option__str,
        p2.item_total_option_jump as item_equipment_preset_2__total_option__jump,
        p2.item_total_option_armor as item_equipment_preset_2__total_option__armor,
        p2.item_total_option_speed as item_equipment_preset_2__total_option__speed,
        p2.item_total_option_damage as item_equipment_preset_2__total_option__damage,
        p2.item_total_option_max_hp as item_equipment_preset_2__total_option__max_hp,
        p2.item_total_option_max_mp as item_equipment_preset_2__total_option__max_mp,
        p2.item_total_option_all_stat as item_equipment_preset_2__total_option__all_stat,
        p2.item_total_option_boss_damage as item_equipment_preset_2__total_option__boss_damage,
        p2.item_total_option_magic_power as item_equipment_preset_2__total_option__magic_power,
        p2.item_total_option_max_hp_rate as item_equipment_preset_2__total_option__max_hp_rate,
        p2.item_total_option_max_mp_rate as item_equipment_preset_2__total_option__max_mp_rate,
        p2.item_total_option_attack_power as item_equipment_preset_2__total_option__attack_power,
        p2.item_total_option_ignore_monster_armor as item_equipment_preset_2__total_option__ignore_monster_armor,
        p2.item_total_option_equipment_level_decrease as item_equipment_preset_2__total_option__equipment_level_decrease,
        p2.has_golden_hammer as has_item_equipment_preset_2__golden_hammer,
        p2.potential_option_1 as item_equipment_preset_2__potential_option_1,
        p2.potential_option_2 as item_equipment_preset_2__potential_option_2,
        p2.potential_option_3 as item_equipment_preset_2__potential_option_3,
        p2.special_ring_level as item_equipment_preset_2__special_ring_level,
        p2.item_starforce_option_dex as item_equipment_preset_2__starforce_option__dex,
        p2.item_starforce_option_int as item_equipment_preset_2__starforce_option__int,
        p2.item_starforce_option_luk as item_equipment_preset_2__starforce_option__luk,
        p2.item_starforce_option_str as item_equipment_preset_2__starforce_option__str,
        p2.item_starforce_option_jump as item_equipment_preset_2__starforce_option__jump,
        p2.item_starforce_option_armor as item_equipment_preset_2__starforce_option__armor,
        p2.item_starforce_option_speed as item_equipment_preset_2__starforce_option__speed,
        p2.item_starforce_option_max_hp as item_equipment_preset_2__starforce_option__max_hp,
        p2.item_starforce_option_max_mp as item_equipment_preset_2__starforce_option__max_mp,
        p2.item_starforce_option_magic_power as item_equipment_preset_2__starforce_option__magic_power,
        p2.item_starforce_option_attack_power as item_equipment_preset_2__starforce_option__attack_power,
        p2.has_potential_option as has_item_equipment_preset_2__potential_option,
        p2.has_starforce_scroll as has_item_equipment_preset_2__starforce_scroll,
        p2.potential_option_grade as item_equipment_preset_2__potential_option_grade,
        p2.item_exceptional_option_dex as item_equipment_preset_2__exceptional_option__dex,
        p2.item_exceptional_option_int as item_equipment_preset_2__exceptional_option__int,
        p2.item_exceptional_option_luk as item_equipment_preset_2__exceptional_option__luk,
        p2.item_exceptional_option_str as item_equipment_preset_2__exceptional_option__str,
        p2.item_exceptional_option_max_hp as item_equipment_preset_2__exceptional_option__max_hp,
        p2.item_exceptional_option_max_mp as item_equipment_preset_2__exceptional_option__max_mp,
        p2.item_exceptional_option_magic_power as item_equipment_preset_2__exceptional_option__magic_power,
        p2.item_exceptional_option_attack_power as item_equipment_preset_2__exceptional_option__attack_power,
        p2.item_exceptional_option_exceptional_upgrade as item_equipment_preset_2__exceptional_option__exceptional_upgrade,
        p2.scroll_resilience_count as item_equipment_preset_2__scroll_resilience_count,
        p2.equipment_level_increase as item_equipment_preset_2__equipment_level_increase,
        p2.scroll_upgradeable_count as item_equipment_preset_2__scroll_upgradeable_count,
        p2.additional_potential_option_1 as item_equipment_preset_2__additional_potential_option_1,
        p2.additional_potential_option_2 as item_equipment_preset_2__additional_potential_option_2,
        p2.additional_potential_option_3 as item_equipment_preset_2__additional_potential_option_3,
        p2.has_additional_potential_option as has_item_equipment_preset_2__additional_potential_option,
        p2.additional_potential_option_grade as item_equipment_preset_2__additional_potential_option_grade,
        p3.item_icon as item_equipment_preset_3__icon,
        p3.item_name as item_equipment_preset_3__name,
        p3.soul_name as item_equipment_preset_3__soul_name,
        p3.starforce as item_equipment_preset_3__starforce,
        p3.growth_exp as item_equipment_preset_3__growth_exp,
        p3.date_expire as item_equipment_preset_3__date_expire,
        p3.item_gender as item_equipment_preset_3__gender,
        p3.soul_option as item_equipment_preset_3__soul_option,
        p3.growth_level as item_equipment_preset_3__growth_level,
        p3.cuttable_count as item_equipment_preset_3__cuttable_count,
        p3.is_freestyle as is_item_equipment_preset_3__freestyle,
        p3.scroll_upgrade as item_equipment_preset_3__scroll_upgrade,
        p3.item_add_option_dex as item_equipment_preset_3__add_option__dex,
        p3.item_add_option_int as item_equipment_preset_3__add_option__int,
        p3.item_add_option_luk as item_equipment_preset_3__add_option__luk,
        p3.item_add_option_str as item_equipment_preset_3__add_option__str,
        p3.item_add_option_jump as item_equipment_preset_3__add_option__jump,
        p3.item_add_option_armor as item_equipment_preset_3__add_option__armor,
        p3.item_add_option_speed as item_equipment_preset_3__add_option__speed,
        p3.item_add_option_damage as item_equipment_preset_3__add_option__damage,
        p3.item_add_option_max_hp as item_equipment_preset_3__add_option__max_hp,
        p3.item_add_option_max_mp as item_equipment_preset_3__add_option__max_mp,
        p3.item_add_option_all_stat as item_equipment_preset_3__add_option__all_stat,
        p3.item_add_option_boss_damage as item_equipment_preset_3__add_option__boss_damage,
        p3.item_add_option_magic_power as item_equipment_preset_3__add_option__magic_power,
        p3.item_add_option_attack_power as item_equipment_preset_3__add_option__attack_power,
        p3.item_add_option_equipment_level_decrease as item_equipment_preset_3__add_option__equipment_level_decrease,
        p3.item_etc_option_dex as item_equipment_preset_3__etc_option__dex,
        p3.item_etc_option_int as item_equipment_preset_3__etc_option__int,
        p3.item_etc_option_luk as item_equipment_preset_3__etc_option__luk,
        p3.item_etc_option_str as item_equipment_preset_3__etc_option__str,
        p3.item_etc_option_jump as item_equipment_preset_3__etc_option__jump,
        p3.item_etc_option_armor as item_equipment_preset_3__etc_option__armor,
        p3.item_etc_option_speed as item_equipment_preset_3__etc_option__speed,
        p3.item_etc_option_max_hp as item_equipment_preset_3__etc_option__max_hp,
        p3.item_etc_option_max_mp as item_equipment_preset_3__etc_option__max_mp,
        p3.item_etc_option_magic_power as item_equipment_preset_3__etc_option__magic_power,
        p3.item_etc_option_attack_power as item_equipment_preset_3__etc_option__attack_power,
        p3.item_shape_icon as item_equipment_preset_3__shape_icon,
        p3.item_shape_name as item_equipment_preset_3__shape_name,
        p3.item_base_option_dex as item_equipment_preset_3__base_option__dex,
        p3.item_base_option_int as item_equipment_preset_3__base_option__int,
        p3.item_base_option_luk as item_equipment_preset_3__base_option__luk,
        p3.item_base_option_str as item_equipment_preset_3__base_option__str,
        p3.item_base_option_jump as item_equipment_preset_3__base_option__jump,
        p3.item_base_option_armor as item_equipment_preset_3__base_option__armor,
        p3.item_base_option_speed as item_equipment_preset_3__base_option__speed,
        p3.item_base_option_max_hp as item_equipment_preset_3__base_option__max_hp,
        p3.item_base_option_max_mp as item_equipment_preset_3__base_option__max_mp,
        p3.item_base_option_all_stat as item_equipment_preset_3__base_option__all_stat,
        p3.item_base_option_boss_damage as item_equipment_preset_3__base_option__boss_damage,
        p3.item_base_option_magic_power as item_equipment_preset_3__base_option__magic_power,
        p3.item_base_option_max_hp_rate as item_equipment_preset_3__base_option__max_hp_rate,
        p3.item_base_option_max_mp_rate as item_equipment_preset_3__base_option__max_mp_rate,
        p3.item_base_option_attack_power as item_equipment_preset_3__base_option__attack_power,
        p3.item_base_option_base_equipment_level as item_equipment_preset_3__base_option__base_equipment_level,
        p3.item_base_option_ignore_monster_armor as item_equipment_preset_3__base_option__ignore_monster_armor,
        p3.item_description as item_equipment_preset_3__description,
        p3.item_total_option_dex as item_equipment_preset_3__total_option__dex,
        p3.item_total_option_int as item_equipment_preset_3__total_option__int,
        p3.item_total_option_luk as item_equipment_preset_3__total_option__luk,
        p3.item_total_option_str as item_equipment_preset_3__total_option__str,
        p3.item_total_option_jump as item_equipment_preset_3__total_option__jump,
        p3.item_total_option_armor as item_equipment_preset_3__total_option__armor,
        p3.item_total_option_speed as item_equipment_preset_3__total_option__speed,
        p3.item_total_option_damage as item_equipment_preset_3__total_option__damage,
        p3.item_total_option_max_hp as item_equipment_preset_3__total_option__max_hp,
        p3.item_total_option_max_mp as item_equipment_preset_3__total_option__max_mp,
        p3.item_total_option_all_stat as item_equipment_preset_3__total_option__all_stat,
        p3.item_total_option_boss_damage as item_equipment_preset_3__total_option__boss_damage,
        p3.item_total_option_magic_power as item_equipment_preset_3__total_option__magic_power,
        p3.item_total_option_max_hp_rate as item_equipment_preset_3__total_option__max_hp_rate,
        p3.item_total_option_max_mp_rate as item_equipment_preset_3__total_option__max_mp_rate,
        p3.item_total_option_attack_power as item_equipment_preset_3__total_option__attack_power,
        p3.item_total_option_ignore_monster_armor as item_equipment_preset_3__total_option__ignore_monster_armor,
        p3.item_total_option_equipment_level_decrease as item_equipment_preset_3__total_option__equipment_level_decrease,
        p3.has_golden_hammer as has_item_equipment_preset_3__golden_hammer,
        p3.potential_option_1 as item_equipment_preset_3__potential_option_1,
        p3.potential_option_2 as item_equipment_preset_3__potential_option_2,
        p3.potential_option_3 as item_equipment_preset_3__potential_option_3,
        p3.special_ring_level as item_equipment_preset_3__special_ring_level,
        p3.item_starforce_option_dex as item_equipment_preset_3__starforce_option__dex,
        p3.item_starforce_option_int as item_equipment_preset_3__starforce_option__int,
        p3.item_starforce_option_luk as item_equipment_preset_3__starforce_option__luk,
        p3.item_starforce_option_str as item_equipment_preset_3__starforce_option__str,
        p3.item_starforce_option_jump as item_equipment_preset_3__starforce_option__jump,
        p3.item_starforce_option_armor as item_equipment_preset_3__starforce_option__armor,
        p3.item_starforce_option_speed as item_equipment_preset_3__starforce_option__speed,
        p3.item_starforce_option_max_hp as item_equipment_preset_3__starforce_option__max_hp,
        p3.item_starforce_option_max_mp as item_equipment_preset_3__starforce_option__max_mp,
        p3.item_starforce_option_magic_power as item_equipment_preset_3__starforce_option__magic_power,
        p3.item_starforce_option_attack_power as item_equipment_preset_3__starforce_option__attack_power,
        p3.has_potential_option as has_item_equipment_preset_3__potential_option,
        p3.has_starforce_scroll as has_item_equipment_preset_3__starforce_scroll,
        p3.potential_option_grade as item_equipment_preset_3__potential_option_grade,
        p3.item_exceptional_option_dex as item_equipment_preset_3__exceptional_option__dex,
        p3.item_exceptional_option_int as item_equipment_preset_3__exceptional_option__int,
        p3.item_exceptional_option_luk as item_equipment_preset_3__exceptional_option__luk,
        p3.item_exceptional_option_str as item_equipment_preset_3__exceptional_option__str,
        p3.item_exceptional_option_max_hp as item_equipment_preset_3__exceptional_option__max_hp,
        p3.item_exceptional_option_max_mp as item_equipment_preset_3__exceptional_option__max_mp,
        p3.item_exceptional_option_magic_power as item_equipment_preset_3__exceptional_option__magic_power,
        p3.item_exceptional_option_attack_power as item_equipment_preset_3__exceptional_option__attack_power,
        p3.item_exceptional_option_exceptional_upgrade as item_equipment_preset_3__exceptional_option__exceptional_upgrade,
        p3.scroll_resilience_count as item_equipment_preset_3__scroll_resilience_count,
        p3.equipment_level_increase as item_equipment_preset_3__equipment_level_increase,
        p3.scroll_upgradeable_count as item_equipment_preset_3__scroll_upgradeable_count,
        p3.additional_potential_option_1 as item_equipment_preset_3__additional_potential_option_1,
        p3.additional_potential_option_2 as item_equipment_preset_3__additional_potential_option_2,
        p3.additional_potential_option_3 as item_equipment_preset_3__additional_potential_option_3,
        p3.has_additional_potential_option as has_item_equipment_preset_3__additional_potential_option,
        p3.additional_potential_option_grade as item_equipment_preset_3__additional_potential_option_grade
    from p1
    full join p2 using (snapshot_date, ocid, item_equipment_slot)
    full join p3 using (snapshot_date, ocid, item_equipment_slot)
),

stg_nexon__character_item_equipments as (
    select
        cie.snapshot_date,
        cie.ocid,
        cie.character_gender,
        cie.character_class,
        cie.preset_no,
        iep.item_equipment_slot,
        iep.item_equipment_part,
        iep.item_equipment_preset_1__icon,
        iep.item_equipment_preset_1__name,
        iep.item_equipment_preset_1__soul_name,
        iep.item_equipment_preset_1__starforce,
        iep.item_equipment_preset_1__growth_exp,
        iep.item_equipment_preset_1__date_expire,
        iep.item_equipment_preset_1__gender,
        iep.item_equipment_preset_1__soul_option,
        iep.item_equipment_preset_1__growth_level,
        iep.item_equipment_preset_1__cuttable_count,
        iep.is_item_equipment_preset_1__freestyle,
        iep.item_equipment_preset_1__scroll_upgrade,
        iep.item_equipment_preset_1__add_option__dex,
        iep.item_equipment_preset_1__add_option__int,
        iep.item_equipment_preset_1__add_option__luk,
        iep.item_equipment_preset_1__add_option__str,
        iep.item_equipment_preset_1__add_option__jump,
        iep.item_equipment_preset_1__add_option__armor,
        iep.item_equipment_preset_1__add_option__speed,
        iep.item_equipment_preset_1__add_option__damage,
        iep.item_equipment_preset_1__add_option__max_hp,
        iep.item_equipment_preset_1__add_option__max_mp,
        iep.item_equipment_preset_1__add_option__all_stat,
        iep.item_equipment_preset_1__add_option__boss_damage,
        iep.item_equipment_preset_1__add_option__magic_power,
        iep.item_equipment_preset_1__add_option__attack_power,
        iep.item_equipment_preset_1__add_option__equipment_level_decrease,
        iep.item_equipment_preset_1__etc_option__dex,
        iep.item_equipment_preset_1__etc_option__int,
        iep.item_equipment_preset_1__etc_option__luk,
        iep.item_equipment_preset_1__etc_option__str,
        iep.item_equipment_preset_1__etc_option__jump,
        iep.item_equipment_preset_1__etc_option__armor,
        iep.item_equipment_preset_1__etc_option__speed,
        iep.item_equipment_preset_1__etc_option__max_hp,
        iep.item_equipment_preset_1__etc_option__max_mp,
        iep.item_equipment_preset_1__etc_option__magic_power,
        iep.item_equipment_preset_1__etc_option__attack_power,
        iep.item_equipment_preset_1__shape_icon,
        iep.item_equipment_preset_1__shape_name,
        iep.item_equipment_preset_1__base_option__dex,
        iep.item_equipment_preset_1__base_option__int,
        iep.item_equipment_preset_1__base_option__luk,
        iep.item_equipment_preset_1__base_option__str,
        iep.item_equipment_preset_1__base_option__jump,
        iep.item_equipment_preset_1__base_option__armor,
        iep.item_equipment_preset_1__base_option__speed,
        iep.item_equipment_preset_1__base_option__max_hp,
        iep.item_equipment_preset_1__base_option__max_mp,
        iep.item_equipment_preset_1__base_option__all_stat,
        iep.item_equipment_preset_1__base_option__boss_damage,
        iep.item_equipment_preset_1__base_option__magic_power,
        iep.item_equipment_preset_1__base_option__max_hp_rate,
        iep.item_equipment_preset_1__base_option__max_mp_rate,
        iep.item_equipment_preset_1__base_option__attack_power,
        iep.item_equipment_preset_1__base_option__base_equipment_level,
        iep.item_equipment_preset_1__base_option__ignore_monster_armor,
        iep.item_equipment_preset_1__description,
        iep.item_equipment_preset_1__total_option__dex,
        iep.item_equipment_preset_1__total_option__int,
        iep.item_equipment_preset_1__total_option__luk,
        iep.item_equipment_preset_1__total_option__str,
        iep.item_equipment_preset_1__total_option__jump,
        iep.item_equipment_preset_1__total_option__armor,
        iep.item_equipment_preset_1__total_option__speed,
        iep.item_equipment_preset_1__total_option__damage,
        iep.item_equipment_preset_1__total_option__max_hp,
        iep.item_equipment_preset_1__total_option__max_mp,
        iep.item_equipment_preset_1__total_option__all_stat,
        iep.item_equipment_preset_1__total_option__boss_damage,
        iep.item_equipment_preset_1__total_option__magic_power,
        iep.item_equipment_preset_1__total_option__max_hp_rate,
        iep.item_equipment_preset_1__total_option__max_mp_rate,
        iep.item_equipment_preset_1__total_option__attack_power,
        iep.item_equipment_preset_1__total_option__ignore_monster_armor,
        iep.item_equipment_preset_1__total_option__equipment_level_decrease,
        iep.has_item_equipment_preset_1__golden_hammer,
        iep.item_equipment_preset_1__potential_option_1,
        iep.item_equipment_preset_1__potential_option_2,
        iep.item_equipment_preset_1__potential_option_3,
        iep.item_equipment_preset_1__special_ring_level,
        iep.item_equipment_preset_1__starforce_option__dex,
        iep.item_equipment_preset_1__starforce_option__int,
        iep.item_equipment_preset_1__starforce_option__luk,
        iep.item_equipment_preset_1__starforce_option__str,
        iep.item_equipment_preset_1__starforce_option__jump,
        iep.item_equipment_preset_1__starforce_option__armor,
        iep.item_equipment_preset_1__starforce_option__speed,
        iep.item_equipment_preset_1__starforce_option__max_hp,
        iep.item_equipment_preset_1__starforce_option__max_mp,
        iep.item_equipment_preset_1__starforce_option__magic_power,
        iep.item_equipment_preset_1__starforce_option__attack_power,
        iep.has_item_equipment_preset_1__potential_option,
        iep.has_item_equipment_preset_1__starforce_scroll,
        iep.item_equipment_preset_1__potential_option_grade,
        iep.item_equipment_preset_1__exceptional_option__dex,
        iep.item_equipment_preset_1__exceptional_option__int,
        iep.item_equipment_preset_1__exceptional_option__luk,
        iep.item_equipment_preset_1__exceptional_option__str,
        iep.item_equipment_preset_1__exceptional_option__max_hp,
        iep.item_equipment_preset_1__exceptional_option__max_mp,
        iep.item_equipment_preset_1__exceptional_option__magic_power,
        iep.item_equipment_preset_1__exceptional_option__attack_power,
        iep.item_equipment_preset_1__exceptional_option__exceptional_upgrade,
        iep.item_equipment_preset_1__scroll_resilience_count,
        iep.item_equipment_preset_1__equipment_level_increase,
        iep.item_equipment_preset_1__scroll_upgradeable_count,
        iep.item_equipment_preset_1__additional_potential_option_1,
        iep.item_equipment_preset_1__additional_potential_option_2,
        iep.item_equipment_preset_1__additional_potential_option_3,
        iep.has_item_equipment_preset_1__additional_potential_option,
        iep.item_equipment_preset_1__additional_potential_option_grade,
        iep.item_equipment_preset_2__icon,
        iep.item_equipment_preset_2__name,
        iep.item_equipment_preset_2__soul_name,
        iep.item_equipment_preset_2__starforce,
        iep.item_equipment_preset_2__growth_exp,
        iep.item_equipment_preset_2__date_expire,
        iep.item_equipment_preset_2__gender,
        iep.item_equipment_preset_2__soul_option,
        iep.item_equipment_preset_2__growth_level,
        iep.item_equipment_preset_2__cuttable_count,
        iep.is_item_equipment_preset_2__freestyle,
        iep.item_equipment_preset_2__scroll_upgrade,
        iep.item_equipment_preset_2__add_option__dex,
        iep.item_equipment_preset_2__add_option__int,
        iep.item_equipment_preset_2__add_option__luk,
        iep.item_equipment_preset_2__add_option__str,
        iep.item_equipment_preset_2__add_option__jump,
        iep.item_equipment_preset_2__add_option__armor,
        iep.item_equipment_preset_2__add_option__speed,
        iep.item_equipment_preset_2__add_option__damage,
        iep.item_equipment_preset_2__add_option__max_hp,
        iep.item_equipment_preset_2__add_option__max_mp,
        iep.item_equipment_preset_2__add_option__all_stat,
        iep.item_equipment_preset_2__add_option__boss_damage,
        iep.item_equipment_preset_2__add_option__magic_power,
        iep.item_equipment_preset_2__add_option__attack_power,
        iep.item_equipment_preset_2__add_option__equipment_level_decrease,
        iep.item_equipment_preset_2__etc_option__dex,
        iep.item_equipment_preset_2__etc_option__int,
        iep.item_equipment_preset_2__etc_option__luk,
        iep.item_equipment_preset_2__etc_option__str,
        iep.item_equipment_preset_2__etc_option__jump,
        iep.item_equipment_preset_2__etc_option__armor,
        iep.item_equipment_preset_2__etc_option__speed,
        iep.item_equipment_preset_2__etc_option__max_hp,
        iep.item_equipment_preset_2__etc_option__max_mp,
        iep.item_equipment_preset_2__etc_option__magic_power,
        iep.item_equipment_preset_2__etc_option__attack_power,
        iep.item_equipment_preset_2__shape_icon,
        iep.item_equipment_preset_2__shape_name,
        iep.item_equipment_preset_2__base_option__dex,
        iep.item_equipment_preset_2__base_option__int,
        iep.item_equipment_preset_2__base_option__luk,
        iep.item_equipment_preset_2__base_option__str,
        iep.item_equipment_preset_2__base_option__jump,
        iep.item_equipment_preset_2__base_option__armor,
        iep.item_equipment_preset_2__base_option__speed,
        iep.item_equipment_preset_2__base_option__max_hp,
        iep.item_equipment_preset_2__base_option__max_mp,
        iep.item_equipment_preset_2__base_option__all_stat,
        iep.item_equipment_preset_2__base_option__boss_damage,
        iep.item_equipment_preset_2__base_option__magic_power,
        iep.item_equipment_preset_2__base_option__max_hp_rate,
        iep.item_equipment_preset_2__base_option__max_mp_rate,
        iep.item_equipment_preset_2__base_option__attack_power,
        iep.item_equipment_preset_2__base_option__base_equipment_level,
        iep.item_equipment_preset_2__base_option__ignore_monster_armor,
        iep.item_equipment_preset_2__description,
        iep.item_equipment_preset_2__total_option__dex,
        iep.item_equipment_preset_2__total_option__int,
        iep.item_equipment_preset_2__total_option__luk,
        iep.item_equipment_preset_2__total_option__str,
        iep.item_equipment_preset_2__total_option__jump,
        iep.item_equipment_preset_2__total_option__armor,
        iep.item_equipment_preset_2__total_option__speed,
        iep.item_equipment_preset_2__total_option__damage,
        iep.item_equipment_preset_2__total_option__max_hp,
        iep.item_equipment_preset_2__total_option__max_mp,
        iep.item_equipment_preset_2__total_option__all_stat,
        iep.item_equipment_preset_2__total_option__boss_damage,
        iep.item_equipment_preset_2__total_option__magic_power,
        iep.item_equipment_preset_2__total_option__max_hp_rate,
        iep.item_equipment_preset_2__total_option__max_mp_rate,
        iep.item_equipment_preset_2__total_option__attack_power,
        iep.item_equipment_preset_2__total_option__ignore_monster_armor,
        iep.item_equipment_preset_2__total_option__equipment_level_decrease,
        iep.has_item_equipment_preset_2__golden_hammer,
        iep.item_equipment_preset_2__potential_option_1,
        iep.item_equipment_preset_2__potential_option_2,
        iep.item_equipment_preset_2__potential_option_3,
        iep.item_equipment_preset_2__special_ring_level,
        iep.item_equipment_preset_2__starforce_option__dex,
        iep.item_equipment_preset_2__starforce_option__int,
        iep.item_equipment_preset_2__starforce_option__luk,
        iep.item_equipment_preset_2__starforce_option__str,
        iep.item_equipment_preset_2__starforce_option__jump,
        iep.item_equipment_preset_2__starforce_option__armor,
        iep.item_equipment_preset_2__starforce_option__speed,
        iep.item_equipment_preset_2__starforce_option__max_hp,
        iep.item_equipment_preset_2__starforce_option__max_mp,
        iep.item_equipment_preset_2__starforce_option__magic_power,
        iep.item_equipment_preset_2__starforce_option__attack_power,
        iep.has_item_equipment_preset_2__potential_option,
        iep.has_item_equipment_preset_2__starforce_scroll,
        iep.item_equipment_preset_2__potential_option_grade,
        iep.item_equipment_preset_2__exceptional_option__dex,
        iep.item_equipment_preset_2__exceptional_option__int,
        iep.item_equipment_preset_2__exceptional_option__luk,
        iep.item_equipment_preset_2__exceptional_option__str,
        iep.item_equipment_preset_2__exceptional_option__max_hp,
        iep.item_equipment_preset_2__exceptional_option__max_mp,
        iep.item_equipment_preset_2__exceptional_option__magic_power,
        iep.item_equipment_preset_2__exceptional_option__attack_power,
        iep.item_equipment_preset_2__exceptional_option__exceptional_upgrade,
        iep.item_equipment_preset_2__scroll_resilience_count,
        iep.item_equipment_preset_2__equipment_level_increase,
        iep.item_equipment_preset_2__scroll_upgradeable_count,
        iep.item_equipment_preset_2__additional_potential_option_1,
        iep.item_equipment_preset_2__additional_potential_option_2,
        iep.item_equipment_preset_2__additional_potential_option_3,
        iep.has_item_equipment_preset_2__additional_potential_option,
        iep.item_equipment_preset_2__additional_potential_option_grade,
        iep.item_equipment_preset_3__icon,
        iep.item_equipment_preset_3__name,
        iep.item_equipment_preset_3__soul_name,
        iep.item_equipment_preset_3__starforce,
        iep.item_equipment_preset_3__growth_exp,
        iep.item_equipment_preset_3__date_expire,
        iep.item_equipment_preset_3__gender,
        iep.item_equipment_preset_3__soul_option,
        iep.item_equipment_preset_3__growth_level,
        iep.item_equipment_preset_3__cuttable_count,
        iep.is_item_equipment_preset_3__freestyle,
        iep.item_equipment_preset_3__scroll_upgrade,
        iep.item_equipment_preset_3__add_option__dex,
        iep.item_equipment_preset_3__add_option__int,
        iep.item_equipment_preset_3__add_option__luk,
        iep.item_equipment_preset_3__add_option__str,
        iep.item_equipment_preset_3__add_option__jump,
        iep.item_equipment_preset_3__add_option__armor,
        iep.item_equipment_preset_3__add_option__speed,
        iep.item_equipment_preset_3__add_option__damage,
        iep.item_equipment_preset_3__add_option__max_hp,
        iep.item_equipment_preset_3__add_option__max_mp,
        iep.item_equipment_preset_3__add_option__all_stat,
        iep.item_equipment_preset_3__add_option__boss_damage,
        iep.item_equipment_preset_3__add_option__magic_power,
        iep.item_equipment_preset_3__add_option__attack_power,
        iep.item_equipment_preset_3__add_option__equipment_level_decrease,
        iep.item_equipment_preset_3__etc_option__dex,
        iep.item_equipment_preset_3__etc_option__int,
        iep.item_equipment_preset_3__etc_option__luk,
        iep.item_equipment_preset_3__etc_option__str,
        iep.item_equipment_preset_3__etc_option__jump,
        iep.item_equipment_preset_3__etc_option__armor,
        iep.item_equipment_preset_3__etc_option__speed,
        iep.item_equipment_preset_3__etc_option__max_hp,
        iep.item_equipment_preset_3__etc_option__max_mp,
        iep.item_equipment_preset_3__etc_option__magic_power,
        iep.item_equipment_preset_3__etc_option__attack_power,
        iep.item_equipment_preset_3__shape_icon,
        iep.item_equipment_preset_3__shape_name,
        iep.item_equipment_preset_3__base_option__dex,
        iep.item_equipment_preset_3__base_option__int,
        iep.item_equipment_preset_3__base_option__luk,
        iep.item_equipment_preset_3__base_option__str,
        iep.item_equipment_preset_3__base_option__jump,
        iep.item_equipment_preset_3__base_option__armor,
        iep.item_equipment_preset_3__base_option__speed,
        iep.item_equipment_preset_3__base_option__max_hp,
        iep.item_equipment_preset_3__base_option__max_mp,
        iep.item_equipment_preset_3__base_option__all_stat,
        iep.item_equipment_preset_3__base_option__boss_damage,
        iep.item_equipment_preset_3__base_option__magic_power,
        iep.item_equipment_preset_3__base_option__max_hp_rate,
        iep.item_equipment_preset_3__base_option__max_mp_rate,
        iep.item_equipment_preset_3__base_option__attack_power,
        iep.item_equipment_preset_3__base_option__base_equipment_level,
        iep.item_equipment_preset_3__base_option__ignore_monster_armor,
        iep.item_equipment_preset_3__description,
        iep.item_equipment_preset_3__total_option__dex,
        iep.item_equipment_preset_3__total_option__int,
        iep.item_equipment_preset_3__total_option__luk,
        iep.item_equipment_preset_3__total_option__str,
        iep.item_equipment_preset_3__total_option__jump,
        iep.item_equipment_preset_3__total_option__armor,
        iep.item_equipment_preset_3__total_option__speed,
        iep.item_equipment_preset_3__total_option__damage,
        iep.item_equipment_preset_3__total_option__max_hp,
        iep.item_equipment_preset_3__total_option__max_mp,
        iep.item_equipment_preset_3__total_option__all_stat,
        iep.item_equipment_preset_3__total_option__boss_damage,
        iep.item_equipment_preset_3__total_option__magic_power,
        iep.item_equipment_preset_3__total_option__max_hp_rate,
        iep.item_equipment_preset_3__total_option__max_mp_rate,
        iep.item_equipment_preset_3__total_option__attack_power,
        iep.item_equipment_preset_3__total_option__ignore_monster_armor,
        iep.item_equipment_preset_3__total_option__equipment_level_decrease,
        iep.has_item_equipment_preset_3__golden_hammer,
        iep.item_equipment_preset_3__potential_option_1,
        iep.item_equipment_preset_3__potential_option_2,
        iep.item_equipment_preset_3__potential_option_3,
        iep.item_equipment_preset_3__special_ring_level,
        iep.item_equipment_preset_3__starforce_option__dex,
        iep.item_equipment_preset_3__starforce_option__int,
        iep.item_equipment_preset_3__starforce_option__luk,
        iep.item_equipment_preset_3__starforce_option__str,
        iep.item_equipment_preset_3__starforce_option__jump,
        iep.item_equipment_preset_3__starforce_option__armor,
        iep.item_equipment_preset_3__starforce_option__speed,
        iep.item_equipment_preset_3__starforce_option__max_hp,
        iep.item_equipment_preset_3__starforce_option__max_mp,
        iep.item_equipment_preset_3__starforce_option__magic_power,
        iep.item_equipment_preset_3__starforce_option__attack_power,
        iep.has_item_equipment_preset_3__potential_option,
        iep.has_item_equipment_preset_3__starforce_scroll,
        iep.item_equipment_preset_3__potential_option_grade,
        iep.item_equipment_preset_3__exceptional_option__dex,
        iep.item_equipment_preset_3__exceptional_option__int,
        iep.item_equipment_preset_3__exceptional_option__luk,
        iep.item_equipment_preset_3__exceptional_option__str,
        iep.item_equipment_preset_3__exceptional_option__max_hp,
        iep.item_equipment_preset_3__exceptional_option__max_mp,
        iep.item_equipment_preset_3__exceptional_option__magic_power,
        iep.item_equipment_preset_3__exceptional_option__attack_power,
        iep.item_equipment_preset_3__exceptional_option__exceptional_upgrade,
        iep.item_equipment_preset_3__scroll_resilience_count,
        iep.item_equipment_preset_3__equipment_level_increase,
        iep.item_equipment_preset_3__scroll_upgradeable_count,
        iep.item_equipment_preset_3__additional_potential_option_1,
        iep.item_equipment_preset_3__additional_potential_option_2,
        iep.item_equipment_preset_3__additional_potential_option_3,
        iep.has_item_equipment_preset_3__additional_potential_option,
        iep.item_equipment_preset_3__additional_potential_option_grade
    from character_item_equipment as cie
    left join item_equipment_presets as iep
        on cie.ocid = iep.ocid and cie.snapshot_date = iep.snapshot_date
)

select * from stg_nexon__character_item_equipments
