with character_cash_item_equipment as (
    select * from {{ source('nexon', 'character_cash_item_equipment') }}
),

c_base as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_base) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

c_p1 as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_preset_1) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

c_p2 as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_preset_2) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

c_p3 as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_preset_3) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_base as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_base) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_p1 as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_preset_1) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_p2 as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_preset_2) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_p3 as (
    select
        date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        el ->> 'freestyle_flag' as freestyle_flag,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_preset_3) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

cash_item_equipment_presets as (
    select
        date,
        ocid,
        cash_item_equipment_slot,
        coalesce(c_base.cash_item_equipment_part, c_p1.cash_item_equipment_part, c_p2.cash_item_equipment_part, c_p3.cash_item_equipment_part, a_base.cash_item_equipment_part, a_p1.cash_item_equipment_part, a_p2.cash_item_equipment_part, a_p3.cash_item_equipment_part) as cash_item_equipment_part,
        c_base.skills as cash_item_equipment_base_skills,
        c_base.date_expire as cash_item_equipment_base_date_expire,
        c_base.item_gender as cash_item_equipment_base_item_gender,
        c_base.emotion_name as cash_item_equipment_base_emotion_name,
        c_base.cash_item_icon as cash_item_equipment_base_cash_item_icon,
        c_base.cash_item_name as cash_item_equipment_base_cash_item_name,
        c_base.freestyle_flag as cash_item_equipment_base_freestyle_flag,
        c_base.cash_item_label as cash_item_equipment_base_cash_item_label,
        c_base.cash_item_option as cash_item_equipment_base_cash_item_option,
        c_base.cash_item_option_str as cash_item_equipment_base_cash_item_option_str,
        c_base.cash_item_option_dex as cash_item_equipment_base_cash_item_option_dex,
        c_base.cash_item_option_int as cash_item_equipment_base_cash_item_option_int,
        c_base.cash_item_option_luk as cash_item_equipment_base_cash_item_option_luk,
        c_base.cash_item_option_max_hp as cash_item_equipment_base_cash_item_option_max_hp,
        c_base.cash_item_option_max_mp as cash_item_equipment_base_cash_item_option_max_mp,
        c_base.cash_item_option_attack_power as cash_item_equipment_base_cash_item_option_attack_power,
        c_base.cash_item_option_magic_power as cash_item_equipment_base_cash_item_option_magic_power,
        c_base.date_option_expire as cash_item_equipment_base_date_option_expire,
        c_base.cash_item_description as cash_item_equipment_base_cash_item_description,
        c_base.cash_item_effect_prism as cash_item_equipment_base_cash_item_effect_prism,
        c_base.cash_item_coloring_prism as cash_item_equipment_base_cash_item_coloring_prism,
        c_p1.skills as cash_item_equipment_preset_1_skills,
        c_p1.date_expire as cash_item_equipment_preset_1_date_expire,
        c_p1.item_gender as cash_item_equipment_preset_1_item_gender,
        c_p1.emotion_name as cash_item_equipment_preset_1_emotion_name,
        c_p1.cash_item_icon as cash_item_equipment_preset_1_cash_item_icon,
        c_p1.cash_item_name as cash_item_equipment_preset_1_cash_item_name,
        c_p1.freestyle_flag as cash_item_equipment_preset_1_freestyle_flag,
        c_p1.cash_item_label as cash_item_equipment_preset_1_cash_item_label,
        c_p1.cash_item_option as cash_item_equipment_preset_1_cash_item_option,
        c_p1.cash_item_option_str as cash_item_equipment_preset_1_cash_item_option_str,
        c_p1.cash_item_option_dex as cash_item_equipment_preset_1_cash_item_option_dex,
        c_p1.cash_item_option_int as cash_item_equipment_preset_1_cash_item_option_int,
        c_p1.cash_item_option_luk as cash_item_equipment_preset_1_cash_item_option_luk,
        c_p1.cash_item_option_max_hp as cash_item_equipment_preset_1_cash_item_option_max_hp,
        c_p1.cash_item_option_max_mp as cash_item_equipment_preset_1_cash_item_option_max_mp,
        c_p1.cash_item_option_attack_power as cash_item_equipment_preset_1_cash_item_option_attack_power,
        c_p1.cash_item_option_magic_power as cash_item_equipment_preset_1_cash_item_option_magic_power,
        c_p1.date_option_expire as cash_item_equipment_preset_1_date_option_expire,
        c_p1.cash_item_description as cash_item_equipment_preset_1_cash_item_description,
        c_p1.cash_item_effect_prism as cash_item_equipment_preset_1_cash_item_effect_prism,
        c_p1.cash_item_coloring_prism as cash_item_equipment_preset_1_cash_item_coloring_prism,
        c_p2.skills as cash_item_equipment_preset_2_skills,
        c_p2.date_expire as cash_item_equipment_preset_2_date_expire,
        c_p2.item_gender as cash_item_equipment_preset_2_item_gender,
        c_p2.emotion_name as cash_item_equipment_preset_2_emotion_name,
        c_p2.cash_item_icon as cash_item_equipment_preset_2_cash_item_icon,
        c_p2.cash_item_name as cash_item_equipment_preset_2_cash_item_name,
        c_p2.freestyle_flag as cash_item_equipment_preset_2_freestyle_flag,
        c_p2.cash_item_label as cash_item_equipment_preset_2_cash_item_label,
        c_p2.cash_item_option as cash_item_equipment_preset_2_cash_item_option,
        c_p2.cash_item_option_str as cash_item_equipment_preset_2_cash_item_option_str,
        c_p2.cash_item_option_dex as cash_item_equipment_preset_2_cash_item_option_dex,
        c_p2.cash_item_option_int as cash_item_equipment_preset_2_cash_item_option_int,
        c_p2.cash_item_option_luk as cash_item_equipment_preset_2_cash_item_option_luk,
        c_p2.cash_item_option_max_hp as cash_item_equipment_preset_2_cash_item_option_max_hp,
        c_p2.cash_item_option_max_mp as cash_item_equipment_preset_2_cash_item_option_max_mp,
        c_p2.cash_item_option_attack_power as cash_item_equipment_preset_2_cash_item_option_attack_power,
        c_p2.cash_item_option_magic_power as cash_item_equipment_preset_2_cash_item_option_magic_power,
        c_p2.date_option_expire as cash_item_equipment_preset_2_date_option_expire,
        c_p2.cash_item_description as cash_item_equipment_preset_2_cash_item_description,
        c_p2.cash_item_effect_prism as cash_item_equipment_preset_2_cash_item_effect_prism,
        c_p2.cash_item_coloring_prism as cash_item_equipment_preset_2_cash_item_coloring_prism,
        c_p3.skills as cash_item_equipment_preset_3_skills,
        c_p3.date_expire as cash_item_equipment_preset_3_date_expire,
        c_p3.item_gender as cash_item_equipment_preset_3_item_gender,
        c_p3.emotion_name as cash_item_equipment_preset_3_emotion_name,
        c_p3.cash_item_icon as cash_item_equipment_preset_3_cash_item_icon,
        c_p3.cash_item_name as cash_item_equipment_preset_3_cash_item_name,
        c_p3.freestyle_flag as cash_item_equipment_preset_3_freestyle_flag,
        c_p3.cash_item_label as cash_item_equipment_preset_3_cash_item_label,
        c_p3.cash_item_option as cash_item_equipment_preset_3_cash_item_option,
        c_p3.cash_item_option_str as cash_item_equipment_preset_3_cash_item_option_str,
        c_p3.cash_item_option_dex as cash_item_equipment_preset_3_cash_item_option_dex,
        c_p3.cash_item_option_int as cash_item_equipment_preset_3_cash_item_option_int,
        c_p3.cash_item_option_luk as cash_item_equipment_preset_3_cash_item_option_luk,
        c_p3.cash_item_option_max_hp as cash_item_equipment_preset_3_cash_item_option_max_hp,
        c_p3.cash_item_option_max_mp as cash_item_equipment_preset_3_cash_item_option_max_mp,
        c_p3.cash_item_option_attack_power as cash_item_equipment_preset_3_cash_item_option_attack_power,
        c_p3.cash_item_option_magic_power as cash_item_equipment_preset_3_cash_item_option_magic_power,
        c_p3.date_option_expire as cash_item_equipment_preset_3_date_option_expire,
        c_p3.cash_item_description as cash_item_equipment_preset_3_cash_item_description,
        c_p3.cash_item_effect_prism as cash_item_equipment_preset_3_cash_item_effect_prism,
        c_p3.cash_item_coloring_prism as cash_item_equipment_preset_3_cash_item_coloring_prism,
        a_base.skills as additional_cash_item_equipment_base_skills,
        a_base.date_expire as additional_cash_item_equipment_base_date_expire,
        a_base.item_gender as additional_cash_item_equipment_base_item_gender,
        a_base.emotion_name as additional_cash_item_equipment_base_emotion_name,
        a_base.cash_item_icon as additional_cash_item_equipment_base_cash_item_icon,
        a_base.cash_item_name as additional_cash_item_equipment_base_cash_item_name,
        a_base.freestyle_flag as additional_cash_item_equipment_base_freestyle_flag,
        a_base.cash_item_label as additional_cash_item_equipment_base_cash_item_label,
        a_base.cash_item_option as additional_cash_item_equipment_base_cash_item_option,
        a_base.cash_item_option_str as additional_cash_item_equipment_base_cash_item_option_str,
        a_base.cash_item_option_dex as additional_cash_item_equipment_base_cash_item_option_dex,
        a_base.cash_item_option_int as additional_cash_item_equipment_base_cash_item_option_int,
        a_base.cash_item_option_luk as additional_cash_item_equipment_base_cash_item_option_luk,
        a_base.cash_item_option_max_hp as additional_cash_item_equipment_base_cash_item_option_max_hp,
        a_base.cash_item_option_max_mp as additional_cash_item_equipment_base_cash_item_option_max_mp,
        a_base.cash_item_option_attack_power as additional_cash_item_equipment_base_cash_item_option_attack_power,
        a_base.cash_item_option_magic_power as additional_cash_item_equipment_base_cash_item_option_magic_power,
        a_base.date_option_expire as additional_cash_item_equipment_base_date_option_expire,
        a_base.cash_item_description as additional_cash_item_equipment_base_cash_item_description,
        a_base.cash_item_effect_prism as additional_cash_item_equipment_base_cash_item_effect_prism,
        a_base.cash_item_coloring_prism as additional_cash_item_equipment_base_cash_item_coloring_prism,
        a_p1.skills as additional_cash_item_equipment_preset_1_skills,
        a_p1.date_expire as additional_cash_item_equipment_preset_1_date_expire,
        a_p1.item_gender as additional_cash_item_equipment_preset_1_item_gender,
        a_p1.emotion_name as additional_cash_item_equipment_preset_1_emotion_name,
        a_p1.cash_item_icon as additional_cash_item_equipment_preset_1_cash_item_icon,
        a_p1.cash_item_name as additional_cash_item_equipment_preset_1_cash_item_name,
        a_p1.freestyle_flag as additional_cash_item_equipment_preset_1_freestyle_flag,
        a_p1.cash_item_label as additional_cash_item_equipment_preset_1_cash_item_label,
        a_p1.cash_item_option as additional_cash_item_equipment_preset_1_cash_item_option,
        a_p1.cash_item_option_str as additional_cash_item_equipment_preset_1_cash_item_option_str,
        a_p1.cash_item_option_dex as additional_cash_item_equipment_preset_1_cash_item_option_dex,
        a_p1.cash_item_option_int as additional_cash_item_equipment_preset_1_cash_item_option_int,
        a_p1.cash_item_option_luk as additional_cash_item_equipment_preset_1_cash_item_option_luk,
        a_p1.cash_item_option_max_hp as additional_cash_item_equipment_preset_1_cash_item_option_max_hp,
        a_p1.cash_item_option_max_mp as additional_cash_item_equipment_preset_1_cash_item_option_max_mp,
        a_p1.cash_item_option_attack_power as additional_cash_item_equipment_preset_1_cash_item_option_attack_power,
        a_p1.cash_item_option_magic_power as additional_cash_item_equipment_preset_1_cash_item_option_magic_power,
        a_p1.date_option_expire as additional_cash_item_equipment_preset_1_date_option_expire,
        a_p1.cash_item_description as additional_cash_item_equipment_preset_1_cash_item_description,
        a_p1.cash_item_effect_prism as additional_cash_item_equipment_preset_1_cash_item_effect_prism,
        a_p1.cash_item_coloring_prism as additional_cash_item_equipment_preset_1_cash_item_coloring_prism,
        a_p2.skills as additional_cash_item_equipment_preset_2_skills,
        a_p2.date_expire as additional_cash_item_equipment_preset_2_date_expire,
        a_p2.item_gender as additional_cash_item_equipment_preset_2_item_gender,
        a_p2.emotion_name as additional_cash_item_equipment_preset_2_emotion_name,
        a_p2.cash_item_icon as additional_cash_item_equipment_preset_2_cash_item_icon,
        a_p2.cash_item_name as additional_cash_item_equipment_preset_2_cash_item_name,
        a_p2.freestyle_flag as additional_cash_item_equipment_preset_2_freestyle_flag,
        a_p2.cash_item_label as additional_cash_item_equipment_preset_2_cash_item_label,
        a_p2.cash_item_option as additional_cash_item_equipment_preset_2_cash_item_option,
        a_p2.cash_item_option_str as additional_cash_item_equipment_preset_2_cash_item_option_str,
        a_p2.cash_item_option_dex as additional_cash_item_equipment_preset_2_cash_item_option_dex,
        a_p2.cash_item_option_int as additional_cash_item_equipment_preset_2_cash_item_option_int,
        a_p2.cash_item_option_luk as additional_cash_item_equipment_preset_2_cash_item_option_luk,
        a_p2.cash_item_option_max_hp as additional_cash_item_equipment_preset_2_cash_item_option_max_hp,
        a_p2.cash_item_option_max_mp as additional_cash_item_equipment_preset_2_cash_item_option_max_mp,
        a_p2.cash_item_option_attack_power as additional_cash_item_equipment_preset_2_cash_item_option_attack_power,
        a_p2.cash_item_option_magic_power as additional_cash_item_equipment_preset_2_cash_item_option_magic_power,
        a_p2.date_option_expire as additional_cash_item_equipment_preset_2_date_option_expire,
        a_p2.cash_item_description as additional_cash_item_equipment_preset_2_cash_item_description,
        a_p2.cash_item_effect_prism as additional_cash_item_equipment_preset_2_cash_item_effect_prism,
        a_p2.cash_item_coloring_prism as additional_cash_item_equipment_preset_2_cash_item_coloring_prism,
        a_p3.skills as additional_cash_item_equipment_preset_3_skills,
        a_p3.date_expire as additional_cash_item_equipment_preset_3_date_expire,
        a_p3.item_gender as additional_cash_item_equipment_preset_3_item_gender,
        a_p3.emotion_name as additional_cash_item_equipment_preset_3_emotion_name,
        a_p3.cash_item_icon as additional_cash_item_equipment_preset_3_cash_item_icon,
        a_p3.cash_item_name as additional_cash_item_equipment_preset_3_cash_item_name,
        a_p3.freestyle_flag as additional_cash_item_equipment_preset_3_freestyle_flag,
        a_p3.cash_item_label as additional_cash_item_equipment_preset_3_cash_item_label,
        a_p3.cash_item_option as additional_cash_item_equipment_preset_3_cash_item_option,
        a_p3.cash_item_option_str as additional_cash_item_equipment_preset_3_cash_item_option_str,
        a_p3.cash_item_option_dex as additional_cash_item_equipment_preset_3_cash_item_option_dex,
        a_p3.cash_item_option_int as additional_cash_item_equipment_preset_3_cash_item_option_int,
        a_p3.cash_item_option_luk as additional_cash_item_equipment_preset_3_cash_item_option_luk,
        a_p3.cash_item_option_max_hp as additional_cash_item_equipment_preset_3_cash_item_option_max_hp,
        a_p3.cash_item_option_max_mp as additional_cash_item_equipment_preset_3_cash_item_option_max_mp,
        a_p3.cash_item_option_attack_power as additional_cash_item_equipment_preset_3_cash_item_option_attack_power,
        a_p3.cash_item_option_magic_power as additional_cash_item_equipment_preset_3_cash_item_option_magic_power,
        a_p3.date_option_expire as additional_cash_item_equipment_preset_3_date_option_expire,
        a_p3.cash_item_description as additional_cash_item_equipment_preset_3_cash_item_description,
        a_p3.cash_item_effect_prism as additional_cash_item_equipment_preset_3_cash_item_effect_prism,
        a_p3.cash_item_coloring_prism as additional_cash_item_equipment_preset_3_cash_item_coloring_prism
    from c_base
    full join c_p1 using (date, ocid, cash_item_equipment_slot)
    full join c_p2 using (date, ocid, cash_item_equipment_slot)
    full join c_p3 using (date, ocid, cash_item_equipment_slot)
    full join a_base using (date, ocid, cash_item_equipment_slot)
    full join a_p1 using (date, ocid, cash_item_equipment_slot)
    full join a_p2 using (date, ocid, cash_item_equipment_slot)
    full join a_p3 using (date, ocid, cash_item_equipment_slot)
),

stg_nexon__character_cash_item_equipment as (
    select
        ccie.date,
        ccie.ocid,
        ciep.cash_item_equipment_part,
        ciep.cash_item_equipment_slot,
        ccie.character_gender,
        ccie.character_class,
        ccie.character_look_mode,
        ciep.cash_item_equipment_base_skills,
        ciep.cash_item_equipment_base_date_expire,
        ciep.cash_item_equipment_base_item_gender,
        ciep.cash_item_equipment_base_emotion_name,
        ciep.cash_item_equipment_base_cash_item_icon,
        ciep.cash_item_equipment_base_cash_item_name,
        ciep.cash_item_equipment_base_freestyle_flag,
        ciep.cash_item_equipment_base_cash_item_label,
        ciep.cash_item_equipment_base_cash_item_option,
        ciep.cash_item_equipment_base_cash_item_option_str,
        ciep.cash_item_equipment_base_cash_item_option_dex,
        ciep.cash_item_equipment_base_cash_item_option_int,
        ciep.cash_item_equipment_base_cash_item_option_luk,
        ciep.cash_item_equipment_base_cash_item_option_max_hp,
        ciep.cash_item_equipment_base_cash_item_option_max_mp,
        ciep.cash_item_equipment_base_cash_item_option_attack_power,
        ciep.cash_item_equipment_base_cash_item_option_magic_power,
        ciep.cash_item_equipment_base_date_option_expire,
        ciep.cash_item_equipment_base_cash_item_description,
        ciep.cash_item_equipment_base_cash_item_effect_prism,
        ciep.cash_item_equipment_base_cash_item_coloring_prism,
        ciep.cash_item_equipment_preset_1_skills,
        ciep.cash_item_equipment_preset_1_date_expire,
        ciep.cash_item_equipment_preset_1_item_gender,
        ciep.cash_item_equipment_preset_1_emotion_name,
        ciep.cash_item_equipment_preset_1_cash_item_icon,
        ciep.cash_item_equipment_preset_1_cash_item_name,
        ciep.cash_item_equipment_preset_1_freestyle_flag,
        ciep.cash_item_equipment_preset_1_cash_item_label,
        ciep.cash_item_equipment_preset_1_cash_item_option,
        ciep.cash_item_equipment_preset_1_cash_item_option_str,
        ciep.cash_item_equipment_preset_1_cash_item_option_dex,
        ciep.cash_item_equipment_preset_1_cash_item_option_int,
        ciep.cash_item_equipment_preset_1_cash_item_option_luk,
        ciep.cash_item_equipment_preset_1_cash_item_option_max_hp,
        ciep.cash_item_equipment_preset_1_cash_item_option_max_mp,
        ciep.cash_item_equipment_preset_1_cash_item_option_attack_power,
        ciep.cash_item_equipment_preset_1_cash_item_option_magic_power,
        ciep.cash_item_equipment_preset_1_date_option_expire,
        ciep.cash_item_equipment_preset_1_cash_item_description,
        ciep.cash_item_equipment_preset_1_cash_item_effect_prism,
        ciep.cash_item_equipment_preset_1_cash_item_coloring_prism,
        ciep.cash_item_equipment_preset_2_skills,
        ciep.cash_item_equipment_preset_2_date_expire,
        ciep.cash_item_equipment_preset_2_item_gender,
        ciep.cash_item_equipment_preset_2_emotion_name,
        ciep.cash_item_equipment_preset_2_cash_item_icon,
        ciep.cash_item_equipment_preset_2_cash_item_name,
        ciep.cash_item_equipment_preset_2_freestyle_flag,
        ciep.cash_item_equipment_preset_2_cash_item_label,
        ciep.cash_item_equipment_preset_2_cash_item_option,
        ciep.cash_item_equipment_preset_2_cash_item_option_str,
        ciep.cash_item_equipment_preset_2_cash_item_option_dex,
        ciep.cash_item_equipment_preset_2_cash_item_option_int,
        ciep.cash_item_equipment_preset_2_cash_item_option_luk,
        ciep.cash_item_equipment_preset_2_cash_item_option_max_hp,
        ciep.cash_item_equipment_preset_2_cash_item_option_max_mp,
        ciep.cash_item_equipment_preset_2_cash_item_option_attack_power,
        ciep.cash_item_equipment_preset_2_cash_item_option_magic_power,
        ciep.cash_item_equipment_preset_2_date_option_expire,
        ciep.cash_item_equipment_preset_2_cash_item_description,
        ciep.cash_item_equipment_preset_2_cash_item_effect_prism,
        ciep.cash_item_equipment_preset_2_cash_item_coloring_prism,
        ciep.cash_item_equipment_preset_3_skills,
        ciep.cash_item_equipment_preset_3_date_expire,
        ciep.cash_item_equipment_preset_3_item_gender,
        ciep.cash_item_equipment_preset_3_emotion_name,
        ciep.cash_item_equipment_preset_3_cash_item_icon,
        ciep.cash_item_equipment_preset_3_cash_item_name,
        ciep.cash_item_equipment_preset_3_freestyle_flag,
        ciep.cash_item_equipment_preset_3_cash_item_label,
        ciep.cash_item_equipment_preset_3_cash_item_option,
        ciep.cash_item_equipment_preset_3_cash_item_option_str,
        ciep.cash_item_equipment_preset_3_cash_item_option_dex,
        ciep.cash_item_equipment_preset_3_cash_item_option_int,
        ciep.cash_item_equipment_preset_3_cash_item_option_luk,
        ciep.cash_item_equipment_preset_3_cash_item_option_max_hp,
        ciep.cash_item_equipment_preset_3_cash_item_option_max_mp,
        ciep.cash_item_equipment_preset_3_cash_item_option_attack_power,
        ciep.cash_item_equipment_preset_3_cash_item_option_magic_power,
        ciep.cash_item_equipment_preset_3_date_option_expire,
        ciep.cash_item_equipment_preset_3_cash_item_description,
        ciep.cash_item_equipment_preset_3_cash_item_effect_prism,
        ciep.cash_item_equipment_preset_3_cash_item_coloring_prism,
        ciep.additional_cash_item_equipment_base_skills,
        ciep.additional_cash_item_equipment_base_date_expire,
        ciep.additional_cash_item_equipment_base_item_gender,
        ciep.additional_cash_item_equipment_base_emotion_name,
        ciep.additional_cash_item_equipment_base_cash_item_icon,
        ciep.additional_cash_item_equipment_base_cash_item_name,
        ciep.additional_cash_item_equipment_base_freestyle_flag,
        ciep.additional_cash_item_equipment_base_cash_item_label,
        ciep.additional_cash_item_equipment_base_cash_item_option,
        ciep.additional_cash_item_equipment_base_cash_item_option_str,
        ciep.additional_cash_item_equipment_base_cash_item_option_dex,
        ciep.additional_cash_item_equipment_base_cash_item_option_int,
        ciep.additional_cash_item_equipment_base_cash_item_option_luk,
        ciep.additional_cash_item_equipment_base_cash_item_option_max_hp,
        ciep.additional_cash_item_equipment_base_cash_item_option_max_mp,
        ciep.additional_cash_item_equipment_base_cash_item_option_attack_power,
        ciep.additional_cash_item_equipment_base_cash_item_option_magic_power,
        ciep.additional_cash_item_equipment_base_date_option_expire,
        ciep.additional_cash_item_equipment_base_cash_item_description,
        ciep.additional_cash_item_equipment_base_cash_item_effect_prism,
        ciep.additional_cash_item_equipment_base_cash_item_coloring_prism,
        ciep.additional_cash_item_equipment_preset_1_skills,
        ciep.additional_cash_item_equipment_preset_1_date_expire,
        ciep.additional_cash_item_equipment_preset_1_item_gender,
        ciep.additional_cash_item_equipment_preset_1_emotion_name,
        ciep.additional_cash_item_equipment_preset_1_cash_item_icon,
        ciep.additional_cash_item_equipment_preset_1_cash_item_name,
        ciep.additional_cash_item_equipment_preset_1_freestyle_flag,
        ciep.additional_cash_item_equipment_preset_1_cash_item_label,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_str,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_dex,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_int,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_luk,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_max_hp,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_max_mp,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_attack_power,
        ciep.additional_cash_item_equipment_preset_1_cash_item_option_magic_power,
        ciep.additional_cash_item_equipment_preset_1_date_option_expire,
        ciep.additional_cash_item_equipment_preset_1_cash_item_description,
        ciep.additional_cash_item_equipment_preset_1_cash_item_effect_prism,
        ciep.additional_cash_item_equipment_preset_1_cash_item_coloring_prism,
        ciep.additional_cash_item_equipment_preset_2_skills,
        ciep.additional_cash_item_equipment_preset_2_date_expire,
        ciep.additional_cash_item_equipment_preset_2_item_gender,
        ciep.additional_cash_item_equipment_preset_2_emotion_name,
        ciep.additional_cash_item_equipment_preset_2_cash_item_icon,
        ciep.additional_cash_item_equipment_preset_2_cash_item_name,
        ciep.additional_cash_item_equipment_preset_2_freestyle_flag,
        ciep.additional_cash_item_equipment_preset_2_cash_item_label,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_str,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_dex,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_int,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_luk,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_max_hp,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_max_mp,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_attack_power,
        ciep.additional_cash_item_equipment_preset_2_cash_item_option_magic_power,
        ciep.additional_cash_item_equipment_preset_2_date_option_expire,
        ciep.additional_cash_item_equipment_preset_2_cash_item_description,
        ciep.additional_cash_item_equipment_preset_2_cash_item_effect_prism,
        ciep.additional_cash_item_equipment_preset_2_cash_item_coloring_prism,
        ciep.additional_cash_item_equipment_preset_3_skills,
        ciep.additional_cash_item_equipment_preset_3_date_expire,
        ciep.additional_cash_item_equipment_preset_3_item_gender,
        ciep.additional_cash_item_equipment_preset_3_emotion_name,
        ciep.additional_cash_item_equipment_preset_3_cash_item_icon,
        ciep.additional_cash_item_equipment_preset_3_cash_item_name,
        ciep.additional_cash_item_equipment_preset_3_freestyle_flag,
        ciep.additional_cash_item_equipment_preset_3_cash_item_label,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_str,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_dex,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_int,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_luk,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_max_hp,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_max_mp,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_attack_power,
        ciep.additional_cash_item_equipment_preset_3_cash_item_option_magic_power,
        ciep.additional_cash_item_equipment_preset_3_date_option_expire,
        ciep.additional_cash_item_equipment_preset_3_cash_item_description,
        ciep.additional_cash_item_equipment_preset_3_cash_item_effect_prism,
        ciep.additional_cash_item_equipment_preset_3_cash_item_coloring_prism
    from character_cash_item_equipment as ccie
    left join cash_item_equipment_presets as ciep
        on ccie.ocid = ciep.ocid and ccie.date = ciep.date
)

select * from stg_nexon__character_cash_item_equipment
