with character_cash_item_equipment as (
    select
        *,
        date as snapshot_date
    from {{ source('nexon', 'character_cash_item_equipment') }}
),

c_base as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_base) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

c_p1 as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_preset_1) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

c_p2 as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_preset_2) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

c_p3 as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(cash_item_equipment_preset_3) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_base as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_base) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_p1 as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_preset_1) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_p2 as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_preset_2) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

a_p3 as (
    select
        snapshot_date,
        ocid,
        el ->> 'cash_item_equipment_slot' as cash_item_equipment_slot,
        el ->> 'cash_item_equipment_part' as cash_item_equipment_part,
        el -> 'skills' as skills,
        el ->> 'date_expire' as date_expire,
        el ->> 'item_gender' as item_gender,
        el ->> 'emotion_name' as emotion_name,
        el ->> 'cash_item_icon' as cash_item_icon,
        el ->> 'cash_item_name' as cash_item_name,
        (el ->> 'freestyle_flag')::boolean as is_freestyle,
        el ->> 'cash_item_label' as cash_item_label,
        el -> 'cash_item_option' as cash_item_option,
        (opts.opt_obj ->> 'STR')::integer as cash_item_option_str,
        (opts.opt_obj ->> 'DEX')::integer as cash_item_option_dex,
        (opts.opt_obj ->> 'INT')::integer as cash_item_option_int,
        (opts.opt_obj ->> 'LUK')::integer as cash_item_option_luk,
        (opts.opt_obj ->> '최대 HP')::integer as cash_item_option_max_hp,
        (opts.opt_obj ->> '최대 MP')::integer as cash_item_option_max_mp,
        (opts.opt_obj ->> '공격력')::integer as cash_item_option_attack_power,
        (opts.opt_obj ->> '마력')::integer as cash_item_option_magic_power,
        el ->> 'date_option_expire' as date_option_expire,
        el ->> 'cash_item_description' as cash_item_description,
        el -> 'cash_item_effect_prism' as cash_item_effect_prism,
        el -> 'cash_item_coloring_prism' as cash_item_coloring_prism
    from character_cash_item_equipment,
        lateral jsonb_array_elements(additional_cash_item_equipment_preset_3) as el
        left join lateral (
            select jsonb_object_agg(o ->> 'option_type', o ->> 'option_value') as opt_obj
            from jsonb_array_elements(el -> 'cash_item_option') as o
        ) as opts on true
),

cash_item_equipment_presets as (
    select
        snapshot_date,
        ocid,
        cash_item_equipment_slot,
        coalesce(c_base.cash_item_equipment_part, c_p1.cash_item_equipment_part, c_p2.cash_item_equipment_part, c_p3.cash_item_equipment_part, a_base.cash_item_equipment_part, a_p1.cash_item_equipment_part, a_p2.cash_item_equipment_part, a_p3.cash_item_equipment_part) as cash_item_equipment_part,
        c_base.skills as cash_item_equipment_base__skills,
        c_base.date_expire as cash_item_equipment_base__date_expire,
        c_base.item_gender as cash_item_equipment_base__item_gender,
        c_base.emotion_name as cash_item_equipment_base__emotion_name,
        c_base.cash_item_icon as cash_item_equipment_base__icon,
        c_base.cash_item_name as cash_item_equipment_base__name,
        c_base.is_freestyle as is_cash_item_equipment_base__freestyle,
        c_base.cash_item_label as cash_item_equipment_base__label,
        c_base.cash_item_option as cash_item_equipment_base__option,
        c_base.cash_item_option_str as cash_item_equipment_base__option__str,
        c_base.cash_item_option_dex as cash_item_equipment_base__option__dex,
        c_base.cash_item_option_int as cash_item_equipment_base__option__int,
        c_base.cash_item_option_luk as cash_item_equipment_base__option__luk,
        c_base.cash_item_option_max_hp as cash_item_equipment_base__option__max_hp,
        c_base.cash_item_option_max_mp as cash_item_equipment_base__option__max_mp,
        c_base.cash_item_option_attack_power as cash_item_equipment_base__option__attack_power,
        c_base.cash_item_option_magic_power as cash_item_equipment_base__option__magic_power,
        c_base.date_option_expire as cash_item_equipment_base__date_option_expire,
        c_base.cash_item_description as cash_item_equipment_base__description,
        c_base.cash_item_effect_prism as cash_item_equipment_base__effect_prism,
        c_base.cash_item_coloring_prism as cash_item_equipment_base__coloring_prism,
        c_p1.skills as cash_item_equipment_preset_1__skills,
        c_p1.date_expire as cash_item_equipment_preset_1__date_expire,
        c_p1.item_gender as cash_item_equipment_preset_1__item_gender,
        c_p1.emotion_name as cash_item_equipment_preset_1__emotion_name,
        c_p1.cash_item_icon as cash_item_equipment_preset_1__icon,
        c_p1.cash_item_name as cash_item_equipment_preset_1__name,
        c_p1.is_freestyle as is_cash_item_equipment_preset_1__freestyle,
        c_p1.cash_item_label as cash_item_equipment_preset_1__label,
        c_p1.cash_item_option as cash_item_equipment_preset_1__option,
        c_p1.cash_item_option_str as cash_item_equipment_preset_1__option__str,
        c_p1.cash_item_option_dex as cash_item_equipment_preset_1__option__dex,
        c_p1.cash_item_option_int as cash_item_equipment_preset_1__option__int,
        c_p1.cash_item_option_luk as cash_item_equipment_preset_1__option__luk,
        c_p1.cash_item_option_max_hp as cash_item_equipment_preset_1__option__max_hp,
        c_p1.cash_item_option_max_mp as cash_item_equipment_preset_1__option__max_mp,
        c_p1.cash_item_option_attack_power as cash_item_equipment_preset_1__option__attack_power,
        c_p1.cash_item_option_magic_power as cash_item_equipment_preset_1__option__magic_power,
        c_p1.date_option_expire as cash_item_equipment_preset_1__date_option_expire,
        c_p1.cash_item_description as cash_item_equipment_preset_1__description,
        c_p1.cash_item_effect_prism as cash_item_equipment_preset_1__effect_prism,
        c_p1.cash_item_coloring_prism as cash_item_equipment_preset_1__coloring_prism,
        c_p2.skills as cash_item_equipment_preset_2__skills,
        c_p2.date_expire as cash_item_equipment_preset_2__date_expire,
        c_p2.item_gender as cash_item_equipment_preset_2__item_gender,
        c_p2.emotion_name as cash_item_equipment_preset_2__emotion_name,
        c_p2.cash_item_icon as cash_item_equipment_preset_2__icon,
        c_p2.cash_item_name as cash_item_equipment_preset_2__name,
        c_p2.is_freestyle as is_cash_item_equipment_preset_2__freestyle,
        c_p2.cash_item_label as cash_item_equipment_preset_2__label,
        c_p2.cash_item_option as cash_item_equipment_preset_2__option,
        c_p2.cash_item_option_str as cash_item_equipment_preset_2__option__str,
        c_p2.cash_item_option_dex as cash_item_equipment_preset_2__option__dex,
        c_p2.cash_item_option_int as cash_item_equipment_preset_2__option__int,
        c_p2.cash_item_option_luk as cash_item_equipment_preset_2__option__luk,
        c_p2.cash_item_option_max_hp as cash_item_equipment_preset_2__option__max_hp,
        c_p2.cash_item_option_max_mp as cash_item_equipment_preset_2__option__max_mp,
        c_p2.cash_item_option_attack_power as cash_item_equipment_preset_2__option__attack_power,
        c_p2.cash_item_option_magic_power as cash_item_equipment_preset_2__option__magic_power,
        c_p2.date_option_expire as cash_item_equipment_preset_2__date_option_expire,
        c_p2.cash_item_description as cash_item_equipment_preset_2__description,
        c_p2.cash_item_effect_prism as cash_item_equipment_preset_2__effect_prism,
        c_p2.cash_item_coloring_prism as cash_item_equipment_preset_2__coloring_prism,
        c_p3.skills as cash_item_equipment_preset_3__skills,
        c_p3.date_expire as cash_item_equipment_preset_3__date_expire,
        c_p3.item_gender as cash_item_equipment_preset_3__item_gender,
        c_p3.emotion_name as cash_item_equipment_preset_3__emotion_name,
        c_p3.cash_item_icon as cash_item_equipment_preset_3__icon,
        c_p3.cash_item_name as cash_item_equipment_preset_3__name,
        c_p3.is_freestyle as is_cash_item_equipment_preset_3__freestyle,
        c_p3.cash_item_label as cash_item_equipment_preset_3__label,
        c_p3.cash_item_option as cash_item_equipment_preset_3__option,
        c_p3.cash_item_option_str as cash_item_equipment_preset_3__option__str,
        c_p3.cash_item_option_dex as cash_item_equipment_preset_3__option__dex,
        c_p3.cash_item_option_int as cash_item_equipment_preset_3__option__int,
        c_p3.cash_item_option_luk as cash_item_equipment_preset_3__option__luk,
        c_p3.cash_item_option_max_hp as cash_item_equipment_preset_3__option__max_hp,
        c_p3.cash_item_option_max_mp as cash_item_equipment_preset_3__option__max_mp,
        c_p3.cash_item_option_attack_power as cash_item_equipment_preset_3__option__attack_power,
        c_p3.cash_item_option_magic_power as cash_item_equipment_preset_3__option__magic_power,
        c_p3.date_option_expire as cash_item_equipment_preset_3__date_option_expire,
        c_p3.cash_item_description as cash_item_equipment_preset_3__description,
        c_p3.cash_item_effect_prism as cash_item_equipment_preset_3__effect_prism,
        c_p3.cash_item_coloring_prism as cash_item_equipment_preset_3__coloring_prism,
        a_base.skills as additional_cash_item_equipment_base__skills,
        a_base.date_expire as additional_cash_item_equipment_base__date_expire,
        a_base.item_gender as additional_cash_item_equipment_base__item_gender,
        a_base.emotion_name as additional_cash_item_equipment_base__emotion_name,
        a_base.cash_item_icon as additional_cash_item_equipment_base__icon,
        a_base.cash_item_name as additional_cash_item_equipment_base__name,
        a_base.is_freestyle as is_additional_cash_item_equipment_base__freestyle,
        a_base.cash_item_label as additional_cash_item_equipment_base__label,
        a_base.cash_item_option as additional_cash_item_equipment_base__option,
        a_base.cash_item_option_str as additional_cash_item_equipment_base__option__str,
        a_base.cash_item_option_dex as additional_cash_item_equipment_base__option__dex,
        a_base.cash_item_option_int as additional_cash_item_equipment_base__option__int,
        a_base.cash_item_option_luk as additional_cash_item_equipment_base__option__luk,
        a_base.cash_item_option_max_hp as additional_cash_item_equipment_base__option__max_hp,
        a_base.cash_item_option_max_mp as additional_cash_item_equipment_base__option__max_mp,
        a_base.cash_item_option_attack_power as additional_cash_item_equipment_base__option__attack_power,
        a_base.cash_item_option_magic_power as additional_cash_item_equipment_base__option__magic_power,
        a_base.date_option_expire as additional_cash_item_equipment_base__date_option_expire,
        a_base.cash_item_description as additional_cash_item_equipment_base__description,
        a_base.cash_item_effect_prism as additional_cash_item_equipment_base__effect_prism,
        a_base.cash_item_coloring_prism as additional_cash_item_equipment_base__coloring_prism,
        a_p1.skills as additional_cash_item_equipment_preset_1__skills,
        a_p1.date_expire as additional_cash_item_equipment_preset_1__date_expire,
        a_p1.item_gender as additional_cash_item_equipment_preset_1__item_gender,
        a_p1.emotion_name as additional_cash_item_equipment_preset_1__emotion_name,
        a_p1.cash_item_icon as additional_cash_item_equipment_preset_1__icon,
        a_p1.cash_item_name as additional_cash_item_equipment_preset_1__name,
        a_p1.is_freestyle as is_additional_cash_item_equipment_preset_1__freestyle,
        a_p1.cash_item_label as additional_cash_item_equipment_preset_1__label,
        a_p1.cash_item_option as additional_cash_item_equipment_preset_1__option,
        a_p1.cash_item_option_str as additional_cash_item_equipment_preset_1__option__str,
        a_p1.cash_item_option_dex as additional_cash_item_equipment_preset_1__option__dex,
        a_p1.cash_item_option_int as additional_cash_item_equipment_preset_1__option__int,
        a_p1.cash_item_option_luk as additional_cash_item_equipment_preset_1__option__luk,
        a_p1.cash_item_option_max_hp as additional_cash_item_equipment_preset_1__option__max_hp,
        a_p1.cash_item_option_max_mp as additional_cash_item_equipment_preset_1__option__max_mp,
        a_p1.cash_item_option_attack_power as additional_cash_item_equipment_preset_1__option__attack_power,
        a_p1.cash_item_option_magic_power as additional_cash_item_equipment_preset_1__option__magic_power,
        a_p1.date_option_expire as additional_cash_item_equipment_preset_1__date_option_expire,
        a_p1.cash_item_description as additional_cash_item_equipment_preset_1__description,
        a_p1.cash_item_effect_prism as additional_cash_item_equipment_preset_1__effect_prism,
        a_p1.cash_item_coloring_prism as additional_cash_item_equipment_preset_1__coloring_prism,
        a_p2.skills as additional_cash_item_equipment_preset_2__skills,
        a_p2.date_expire as additional_cash_item_equipment_preset_2__date_expire,
        a_p2.item_gender as additional_cash_item_equipment_preset_2__item_gender,
        a_p2.emotion_name as additional_cash_item_equipment_preset_2__emotion_name,
        a_p2.cash_item_icon as additional_cash_item_equipment_preset_2__icon,
        a_p2.cash_item_name as additional_cash_item_equipment_preset_2__name,
        a_p2.is_freestyle as is_additional_cash_item_equipment_preset_2__freestyle,
        a_p2.cash_item_label as additional_cash_item_equipment_preset_2__label,
        a_p2.cash_item_option as additional_cash_item_equipment_preset_2__option,
        a_p2.cash_item_option_str as additional_cash_item_equipment_preset_2__option__str,
        a_p2.cash_item_option_dex as additional_cash_item_equipment_preset_2__option__dex,
        a_p2.cash_item_option_int as additional_cash_item_equipment_preset_2__option__int,
        a_p2.cash_item_option_luk as additional_cash_item_equipment_preset_2__option__luk,
        a_p2.cash_item_option_max_hp as additional_cash_item_equipment_preset_2__option__max_hp,
        a_p2.cash_item_option_max_mp as additional_cash_item_equipment_preset_2__option__max_mp,
        a_p2.cash_item_option_attack_power as additional_cash_item_equipment_preset_2__option__attack_power,
        a_p2.cash_item_option_magic_power as additional_cash_item_equipment_preset_2__option__magic_power,
        a_p2.date_option_expire as additional_cash_item_equipment_preset_2__date_option_expire,
        a_p2.cash_item_description as additional_cash_item_equipment_preset_2__description,
        a_p2.cash_item_effect_prism as additional_cash_item_equipment_preset_2__effect_prism,
        a_p2.cash_item_coloring_prism as additional_cash_item_equipment_preset_2__coloring_prism,
        a_p3.skills as additional_cash_item_equipment_preset_3__skills,
        a_p3.date_expire as additional_cash_item_equipment_preset_3__date_expire,
        a_p3.item_gender as additional_cash_item_equipment_preset_3__item_gender,
        a_p3.emotion_name as additional_cash_item_equipment_preset_3__emotion_name,
        a_p3.cash_item_icon as additional_cash_item_equipment_preset_3__icon,
        a_p3.cash_item_name as additional_cash_item_equipment_preset_3__name,
        a_p3.is_freestyle as is_additional_cash_item_equipment_preset_3__freestyle,
        a_p3.cash_item_label as additional_cash_item_equipment_preset_3__label,
        a_p3.cash_item_option as additional_cash_item_equipment_preset_3__option,
        a_p3.cash_item_option_str as additional_cash_item_equipment_preset_3__option__str,
        a_p3.cash_item_option_dex as additional_cash_item_equipment_preset_3__option__dex,
        a_p3.cash_item_option_int as additional_cash_item_equipment_preset_3__option__int,
        a_p3.cash_item_option_luk as additional_cash_item_equipment_preset_3__option__luk,
        a_p3.cash_item_option_max_hp as additional_cash_item_equipment_preset_3__option__max_hp,
        a_p3.cash_item_option_max_mp as additional_cash_item_equipment_preset_3__option__max_mp,
        a_p3.cash_item_option_attack_power as additional_cash_item_equipment_preset_3__option__attack_power,
        a_p3.cash_item_option_magic_power as additional_cash_item_equipment_preset_3__option__magic_power,
        a_p3.date_option_expire as additional_cash_item_equipment_preset_3__date_option_expire,
        a_p3.cash_item_description as additional_cash_item_equipment_preset_3__description,
        a_p3.cash_item_effect_prism as additional_cash_item_equipment_preset_3__effect_prism,
        a_p3.cash_item_coloring_prism as additional_cash_item_equipment_preset_3__coloring_prism
    from c_base
    full join c_p1 using (snapshot_date, ocid, cash_item_equipment_slot)
    full join c_p2 using (snapshot_date, ocid, cash_item_equipment_slot)
    full join c_p3 using (snapshot_date, ocid, cash_item_equipment_slot)
    full join a_base using (snapshot_date, ocid, cash_item_equipment_slot)
    full join a_p1 using (snapshot_date, ocid, cash_item_equipment_slot)
    full join a_p2 using (snapshot_date, ocid, cash_item_equipment_slot)
    full join a_p3 using (snapshot_date, ocid, cash_item_equipment_slot)
),

stg_nexon__character_cash_item_equipments as (
    select
        ccie.snapshot_date,
        ccie.ocid,
        ciep.cash_item_equipment_part,
        ciep.cash_item_equipment_slot,
        ccie.character_gender,
        ccie.character_class,
        ccie.character_look_mode,
        ciep.cash_item_equipment_base__skills,
        ciep.cash_item_equipment_base__date_expire,
        ciep.cash_item_equipment_base__item_gender,
        ciep.cash_item_equipment_base__emotion_name,
        ciep.cash_item_equipment_base__icon,
        ciep.cash_item_equipment_base__name,
        ciep.is_cash_item_equipment_base__freestyle,
        ciep.cash_item_equipment_base__label,
        ciep.cash_item_equipment_base__option,
        ciep.cash_item_equipment_base__option__str,
        ciep.cash_item_equipment_base__option__dex,
        ciep.cash_item_equipment_base__option__int,
        ciep.cash_item_equipment_base__option__luk,
        ciep.cash_item_equipment_base__option__max_hp,
        ciep.cash_item_equipment_base__option__max_mp,
        ciep.cash_item_equipment_base__option__attack_power,
        ciep.cash_item_equipment_base__option__magic_power,
        ciep.cash_item_equipment_base__date_option_expire,
        ciep.cash_item_equipment_base__description,
        ciep.cash_item_equipment_base__effect_prism,
        ciep.cash_item_equipment_base__coloring_prism,
        ciep.cash_item_equipment_preset_1__skills,
        ciep.cash_item_equipment_preset_1__date_expire,
        ciep.cash_item_equipment_preset_1__item_gender,
        ciep.cash_item_equipment_preset_1__emotion_name,
        ciep.cash_item_equipment_preset_1__icon,
        ciep.cash_item_equipment_preset_1__name,
        ciep.is_cash_item_equipment_preset_1__freestyle,
        ciep.cash_item_equipment_preset_1__label,
        ciep.cash_item_equipment_preset_1__option,
        ciep.cash_item_equipment_preset_1__option__str,
        ciep.cash_item_equipment_preset_1__option__dex,
        ciep.cash_item_equipment_preset_1__option__int,
        ciep.cash_item_equipment_preset_1__option__luk,
        ciep.cash_item_equipment_preset_1__option__max_hp,
        ciep.cash_item_equipment_preset_1__option__max_mp,
        ciep.cash_item_equipment_preset_1__option__attack_power,
        ciep.cash_item_equipment_preset_1__option__magic_power,
        ciep.cash_item_equipment_preset_1__date_option_expire,
        ciep.cash_item_equipment_preset_1__description,
        ciep.cash_item_equipment_preset_1__effect_prism,
        ciep.cash_item_equipment_preset_1__coloring_prism,
        ciep.cash_item_equipment_preset_2__skills,
        ciep.cash_item_equipment_preset_2__date_expire,
        ciep.cash_item_equipment_preset_2__item_gender,
        ciep.cash_item_equipment_preset_2__emotion_name,
        ciep.cash_item_equipment_preset_2__icon,
        ciep.cash_item_equipment_preset_2__name,
        ciep.is_cash_item_equipment_preset_2__freestyle,
        ciep.cash_item_equipment_preset_2__label,
        ciep.cash_item_equipment_preset_2__option,
        ciep.cash_item_equipment_preset_2__option__str,
        ciep.cash_item_equipment_preset_2__option__dex,
        ciep.cash_item_equipment_preset_2__option__int,
        ciep.cash_item_equipment_preset_2__option__luk,
        ciep.cash_item_equipment_preset_2__option__max_hp,
        ciep.cash_item_equipment_preset_2__option__max_mp,
        ciep.cash_item_equipment_preset_2__option__attack_power,
        ciep.cash_item_equipment_preset_2__option__magic_power,
        ciep.cash_item_equipment_preset_2__date_option_expire,
        ciep.cash_item_equipment_preset_2__description,
        ciep.cash_item_equipment_preset_2__effect_prism,
        ciep.cash_item_equipment_preset_2__coloring_prism,
        ciep.cash_item_equipment_preset_3__skills,
        ciep.cash_item_equipment_preset_3__date_expire,
        ciep.cash_item_equipment_preset_3__item_gender,
        ciep.cash_item_equipment_preset_3__emotion_name,
        ciep.cash_item_equipment_preset_3__icon,
        ciep.cash_item_equipment_preset_3__name,
        ciep.is_cash_item_equipment_preset_3__freestyle,
        ciep.cash_item_equipment_preset_3__label,
        ciep.cash_item_equipment_preset_3__option,
        ciep.cash_item_equipment_preset_3__option__str,
        ciep.cash_item_equipment_preset_3__option__dex,
        ciep.cash_item_equipment_preset_3__option__int,
        ciep.cash_item_equipment_preset_3__option__luk,
        ciep.cash_item_equipment_preset_3__option__max_hp,
        ciep.cash_item_equipment_preset_3__option__max_mp,
        ciep.cash_item_equipment_preset_3__option__attack_power,
        ciep.cash_item_equipment_preset_3__option__magic_power,
        ciep.cash_item_equipment_preset_3__date_option_expire,
        ciep.cash_item_equipment_preset_3__description,
        ciep.cash_item_equipment_preset_3__effect_prism,
        ciep.cash_item_equipment_preset_3__coloring_prism,
        ciep.additional_cash_item_equipment_base__skills,
        ciep.additional_cash_item_equipment_base__date_expire,
        ciep.additional_cash_item_equipment_base__item_gender,
        ciep.additional_cash_item_equipment_base__emotion_name,
        ciep.additional_cash_item_equipment_base__icon,
        ciep.additional_cash_item_equipment_base__name,
        ciep.is_additional_cash_item_equipment_base__freestyle,
        ciep.additional_cash_item_equipment_base__label,
        ciep.additional_cash_item_equipment_base__option,
        ciep.additional_cash_item_equipment_base__option__str,
        ciep.additional_cash_item_equipment_base__option__dex,
        ciep.additional_cash_item_equipment_base__option__int,
        ciep.additional_cash_item_equipment_base__option__luk,
        ciep.additional_cash_item_equipment_base__option__max_hp,
        ciep.additional_cash_item_equipment_base__option__max_mp,
        ciep.additional_cash_item_equipment_base__option__attack_power,
        ciep.additional_cash_item_equipment_base__option__magic_power,
        ciep.additional_cash_item_equipment_base__date_option_expire,
        ciep.additional_cash_item_equipment_base__description,
        ciep.additional_cash_item_equipment_base__effect_prism,
        ciep.additional_cash_item_equipment_base__coloring_prism,
        ciep.additional_cash_item_equipment_preset_1__skills,
        ciep.additional_cash_item_equipment_preset_1__date_expire,
        ciep.additional_cash_item_equipment_preset_1__item_gender,
        ciep.additional_cash_item_equipment_preset_1__emotion_name,
        ciep.additional_cash_item_equipment_preset_1__icon,
        ciep.additional_cash_item_equipment_preset_1__name,
        ciep.is_additional_cash_item_equipment_preset_1__freestyle,
        ciep.additional_cash_item_equipment_preset_1__label,
        ciep.additional_cash_item_equipment_preset_1__option,
        ciep.additional_cash_item_equipment_preset_1__option__str,
        ciep.additional_cash_item_equipment_preset_1__option__dex,
        ciep.additional_cash_item_equipment_preset_1__option__int,
        ciep.additional_cash_item_equipment_preset_1__option__luk,
        ciep.additional_cash_item_equipment_preset_1__option__max_hp,
        ciep.additional_cash_item_equipment_preset_1__option__max_mp,
        ciep.additional_cash_item_equipment_preset_1__option__attack_power,
        ciep.additional_cash_item_equipment_preset_1__option__magic_power,
        ciep.additional_cash_item_equipment_preset_1__date_option_expire,
        ciep.additional_cash_item_equipment_preset_1__description,
        ciep.additional_cash_item_equipment_preset_1__effect_prism,
        ciep.additional_cash_item_equipment_preset_1__coloring_prism,
        ciep.additional_cash_item_equipment_preset_2__skills,
        ciep.additional_cash_item_equipment_preset_2__date_expire,
        ciep.additional_cash_item_equipment_preset_2__item_gender,
        ciep.additional_cash_item_equipment_preset_2__emotion_name,
        ciep.additional_cash_item_equipment_preset_2__icon,
        ciep.additional_cash_item_equipment_preset_2__name,
        ciep.is_additional_cash_item_equipment_preset_2__freestyle,
        ciep.additional_cash_item_equipment_preset_2__label,
        ciep.additional_cash_item_equipment_preset_2__option,
        ciep.additional_cash_item_equipment_preset_2__option__str,
        ciep.additional_cash_item_equipment_preset_2__option__dex,
        ciep.additional_cash_item_equipment_preset_2__option__int,
        ciep.additional_cash_item_equipment_preset_2__option__luk,
        ciep.additional_cash_item_equipment_preset_2__option__max_hp,
        ciep.additional_cash_item_equipment_preset_2__option__max_mp,
        ciep.additional_cash_item_equipment_preset_2__option__attack_power,
        ciep.additional_cash_item_equipment_preset_2__option__magic_power,
        ciep.additional_cash_item_equipment_preset_2__date_option_expire,
        ciep.additional_cash_item_equipment_preset_2__description,
        ciep.additional_cash_item_equipment_preset_2__effect_prism,
        ciep.additional_cash_item_equipment_preset_2__coloring_prism,
        ciep.additional_cash_item_equipment_preset_3__skills,
        ciep.additional_cash_item_equipment_preset_3__date_expire,
        ciep.additional_cash_item_equipment_preset_3__item_gender,
        ciep.additional_cash_item_equipment_preset_3__emotion_name,
        ciep.additional_cash_item_equipment_preset_3__icon,
        ciep.additional_cash_item_equipment_preset_3__name,
        ciep.is_additional_cash_item_equipment_preset_3__freestyle,
        ciep.additional_cash_item_equipment_preset_3__label,
        ciep.additional_cash_item_equipment_preset_3__option,
        ciep.additional_cash_item_equipment_preset_3__option__str,
        ciep.additional_cash_item_equipment_preset_3__option__dex,
        ciep.additional_cash_item_equipment_preset_3__option__int,
        ciep.additional_cash_item_equipment_preset_3__option__luk,
        ciep.additional_cash_item_equipment_preset_3__option__max_hp,
        ciep.additional_cash_item_equipment_preset_3__option__max_mp,
        ciep.additional_cash_item_equipment_preset_3__option__attack_power,
        ciep.additional_cash_item_equipment_preset_3__option__magic_power,
        ciep.additional_cash_item_equipment_preset_3__date_option_expire,
        ciep.additional_cash_item_equipment_preset_3__description,
        ciep.additional_cash_item_equipment_preset_3__effect_prism,
        ciep.additional_cash_item_equipment_preset_3__coloring_prism
    from character_cash_item_equipment as ccie
    left join cash_item_equipment_presets as ciep
        on ccie.ocid = ciep.ocid and ccie.snapshot_date = ciep.snapshot_date
)

select * from stg_nexon__character_cash_item_equipments
